### ISSUE TITLE
How to filter by DocType

### ISSUE THREAD

**Issue by rubengrill** [elastic/elasticsearch-dsl-py#1007]
I'm using elasticsearch 6.3.1 and elasticsarch-dsl 6.2.1.
I have two `DocType`s:

```python
my_index = Index('myindex')

@my_index.document
ArticleDocument(Document):
    text = Text()


@my_index.document
TopicDocument(Document):
    text = Text()
```

The default mapping is `doc` and I therefore I can't use `ArticleDocument.search()` to only get articles back, it will always include topics as well.

I tried `class Meta` with `doc_type = 'article'` as well, but apparently the doc type must be consistent between **all** documents and the index.

So how is the supposed way to use different mappings in the same index to be able to do correct filtering by document type?

**Comment by HonzaKral** [comment]
Since you cannot actually have different types in a single index in elasticsearch 6.x the recommended way is to have a `Keyword` field on the document that will contain the name of the type which you can then filter on. You can also override the class method `search()` on the `Document` classes. You can see (0) for an example.

Hope this helps!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/parent_child.py#L98-L100
