### ISSUE TITLE
Query/filter with term only works on lower case values but not upper case values

### ISSUE THREAD

**Issue by dclong** [elastic/elasticsearch-dsl-py#1030]
My colleague maintains an Elasticsearch database. There is a field named `fm` with all upper case string values (e.g., UBER, FLMS, etc.). When I tried to query ES with the following code it returns no record. 
```
response = Search(using=client, index="some_index") \
    .filter("term", fm="UBER").execute()
```
However, it works if I change `UBER` to lower case.
```
response = Search(using=client, index="some_index") \
    .filter("term", fm="uber").execute()
```
Any idea what's going on?

**Comment by harshanarayana** [comment]
@dclong What's the type for the `fm` property defined in Index Mapping? If the fields are analyzed the Uppercase gets tokenized and indexed as lowercase values but you can still see them in their original format in the Document. Try enabling the `not_analyzed` option of the property

**Comment by HonzaKral** [comment]
exactly as @harshanarayana is saying - you are doing a `term` query (which does not analyze the text) against a field that has been analyzed (is of type `text`). You can either use a `match` query instead of `term` that will properly analyze the text or use a `keyword` field instead. If you haven't specified your mapping you will have a `keyword` field already in `fm.keyword` so you can query it: 
```python
response = Search(using=client, index="some_index") \
    .filter("term", fm__keyword="UBER").execute()
```

Hope this helps!

**Comment by dclong** [comment]
Thank you very much, @harshanarayana and @HonzaKral! Very well explained and I get it now.

**Comment by sayantansinha** [comment]
@HonzaKral  I have a keyword field which stores the value in upper case like "EXCLUSIVE", "HOLDBACK". When I search using a term query using "EXCLUSIVE" it does not return me anything, however, if I search using "exclusive" it returns me the records I want. Aren't keyword supposed to be exact match?
