### ISSUE TITLE
'buckets' key error, when nested aggregation

### ISSUE THREAD

**Issue by BolshakovNO** [elastic/elasticsearch-dsl-py#1036]
```
elasticsearch_dsl/response/aggs.py, line 43, in buckets
    bs = self._d_['buckets']

buckets = {'doc_count': 100, 'nested': {'doc_count_error_upper_bound':...}
search.agg = {  
   'timerange.start':{  
      'nested':{  
         'path':'TIMERANGE'
      },
      'aggs':{  
         'nested':{  
            'terms':{  
               'field':'TIMERANGE.START',
               'order':{  
                  '_key':'desc'
               },
               'size':5
            },
            'aggs':{  
               'priority':{  
                  'reverse_nested':{  

                  },
                  'aggs':{  
                     'reverse_nested':{  
                        'terms':{  
                           'field':'PRIORITY',
                           'size':5
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

```

**Comment by BolshakovNO** [comment]
error raise when check hasattr(buckets, 'buckets')

**Comment by HonzaKral** [comment]
I am sorry but I do not understand what the problem is - what is it that you are trying to do when you encounter this error? I cannot replicate it. Thank you

**Comment by BolshakovNO** [comment]
This is the aggregation structure in request (up in search.agg)

when i get response and try to get (hasattr, getattr whatever) attribute
search.aggregations.buckets, i get error, 'cos there is only 'nested'
attribute, in the root, and buckets is a @property. i do not have problems
with it in previous version.
Think that is bug





чт, 15 нояб. 2018 г. в 17:41, Honza Král <notifications@github.com>:

**Comment by HonzaKral** [comment]
I am sorry, but `search.aggregations.buckets` is not supposed to work as you need to access an aggregation by its name (`timerange.start` in your case) and only *then* access `.buckets` on that aggregation. Since you have a dot in the aggregation name it will not work in this case. Please use a name without a dot and try accessing it via `.aggregations.NAME.buckets`.

I am sorry if I am still not getting your issue right but without code to reproduce it I am not 100% sure what is happening.

**Comment by HonzaKral** [comment]
again I apologize but I am unable to replicate this issue, please feel free to reopen with additional information
