### ISSUE TITLE
Where may I find the document of parameters in Text(),Date(),Nested() and others?

### ISSUE THREAD

**Issue by DachuanZhao** [elastic/elasticsearch-dsl-py#1069]
I can't find it...And I can't find how to index a field with multiple values in class DocType.

**Comment by HonzaKral** [comment]
As with any other objects in the `dsl` - just use the official elasticsearch docs. Any parameter that you can specify in the raw `json` you can pass in as a keyword argument, so
```json
{
          "type":   "date",
          "format": "yyyy-MM-dd"
}
```
becomes `Date(format='yyyy-MM-dd')`. With `nested` you just have to define your mappings by specifying an `InnerDoc` subclass (though passing in `properties` dict works too).

As for multiple values you can specify `multi=True` so that python will always default to a `list` of values, but there is no requirement to do that, just like elasticsearch this library supports multiple values for any field, just assign a list of values to it.

Hope this helps!
