### ISSUE TITLE
DeprecationWarning: The truth value of an empty array is ambiguous

### ISSUE THREAD

**Issue by nicoulaj** [elastic/elasticsearch-dsl-py#1073]
I get this warning on python 3.6.6 with elasticsearch-dsl 6.3.0:
```
.env/lib64/python3.6/site-packages/elasticsearch_dsl/utils.py:463: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
    if v in ([], {}, None):
```

**Comment by HonzaKral** [comment]
This is cased by us comparing the value you gave, which I assume is a `numpy` array, to `False` (https://github.com/numpy/numpy/issues/9583). It is not directly caused by `elasticsearch-dsl` and can be safely ignored.

That said it looks like you are using a `numpy` array on your documents which is not directly supported, we only support python lists.

Hope this helps!
