### ISSUE TITLE
What's the most efficient method to get an Search's attribute?

### ISSUE THREAD

**Issue by DachuanZhao** [elastic/elasticsearch-dsl-py#1100]
Here is my code:
```
class Clsname(DocType):
    attri1 = Text(fields={'raw': Keyword()})
    attri2 = Text(analyzer='whitespace')
```

It costs 0.02s when I search like that:
`result_list = Clsname.search()[0:300].filter().query('match',attri2="attri2")`
But it costs 0.7s when I get attri1 from result_list like that:
`clsname_list = [v.attri1 for v in result_list]`
Is there any more efficient method to get attri1?

**Comment by HonzaKral** [comment]
You can save some time by requesting only the relevant field be sent to you instead of the whole `_source` if you are only interested in the one field, this is especially good if the network is the limitation as opposed to the query time.

You can also turn of calculating the score by using `filter` instead of `query`:
```python
 result_list = Clsname.search()[0:300].filter('match',attri2="attri2")
```

To debug what is taking such a long time I would recommend turning on logging for `elasticsearch-py` (the `elasticsearch` logger in python's `logging` module) and inspecting the `took` parameter in the response which is a number of `ms` that the query took to execute.

hope this helps!
