### ISSUE TITLE
Missing Attachment api in the elasticsearrch_dsl.field module 

### ISSUE THREAD

**Issue by Shivamagrawal2014** [elastic/elasticsearch-dsl-py#1114]
I am unable to find the Attachement Api in the elasticsearch_dsl.field module, how do I pass the attahment in the IngestClient ?

**Comment by HonzaKral** [comment]
I am sorry but I do not know what you are after, could you please provide an example code with raw json or the low level client demonstrating what functionality you are missing?

Thank you!

**Comment by nm523** [comment]
I believe the issue is to do with [this commit](https://github.com/elastic/elasticsearch-dsl-py/commit/21a620d758d13d1ca3d20c36d6db0fead0e8b5fe#diff-38cde0cba5a188e99558e5db2114aec5), when the serialisation updates were applied.

A working example of the Attachment field was posted under issue #760 under [the following comment](https://github.com/elastic/elasticsearch-dsl-py/issues/760#issuecomment-3#40259037).

**Comment by AndresUrregoAngel** [comment]
I'm facing the same issue ` from elasticsearch_dsl.field import Attachment` please if someone knows something I will be following this thread

**Comment by murphydavis** [comment]
Looks like this was somehow a mistake in the merge - I found this myself converting a project to use elasticsearch_dsl just recently. I have added it to my own project for the time being, but I will submit a PR for this.

**Comment by HonzaKral** [comment]
Attachment has been removed from elasticsearch in favor of the attachment ingestion pipeline processor
