### ISSUE TITLE
Field.deserialize changes data in place

### ISSUE THREAD

**Issue by noamkush** [elastic/elasticsearch-dsl-py#1156]
When creating a document from python objects, then saving it, the data is modified in place to have elasticsearch types, which is unexpected, and undesired in my opinion.
See the following example (I took the classes from the docs and simplified them):
```python
In [3]: from elasticsearch_dsl import Document, Nested, InnerDoc, Text

In [4]: class Comment(InnerDoc):
   ...:     author = Text()
   ...:     content = Text()
   ...:

In [5]: class Post(Document):
   ...:     comments = Nested(Comment)
   ...:
   ...:     class Index:
   ...:         name = 'blog'
   ...:

In [6]: my_post = {'comments': [{'author': 'someone', 'content': 'Loved it'}]}

In [7]: my_post
Out[7]: {'comments': [{'author': 'someone', 'content': 'Loved it'}]}

In [8]: doc = Post(**my_post)

In [9]: type(my_post['comments'][0])
Out[9]: dict

In [10]: doc.save()
Out[10]: True

In [11]: type(my_post['comments'][0])
Out[11]: __main__.Comment
```

The relevant code is the following from [field.py](https://github.com/elastic/elasticsearch-dsl-py/blob/e2a4a6d7e6d215dc0471d722fd6d7e369ae78deb/elasticsearch_dsl/field.py#L91):
```python
data[:] = [
    None if d is None else self._deserialize(d)
    for d in data
]
```
I can send a pull request to fix this but I wanted to know whether there's some reasoning for this behavior.

**Comment by HonzaKral** [comment]
Thank you for raising this issue, may I ask why you think this is undesired?

My thinking was always quite the opposite here - ideally in python you work with python objects, when working with nested documents you should really be using the proper objects (`Comment` in this instance) as otherwise you have very inconsistent interface when the objects came from elasticsearch vs if you instantiate them yourself. hitting `.save()` or, more specifically, `full_clean()` will thus nromalize it to the *proper* interface.

Does that make sense?

**Comment by noamkush** [comment]
It makes sense that elasticsearch would use python objects but it doesn't explain why does the `save()` change an object which was given in a constructor and is completely unrelated to the elasticsearch objects. The usual behavior of any other python library would be to create a new list, not modify the existing one.

**Comment by HonzaKral** [comment]
Makes perfect sense, thanks for the report!
