### ISSUE TITLE
Why do we need to inherit from Parent's class (join relationship) ?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [elastic/elasticsearch-dsl-py#1168]
Hi, why do we need to inherit from `Post ` class in this example ?

https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/parent_child.py#L88

Thx in advance !

**Comment by HonzaKral** [comment]
Hi, it is because `Question` needs all the fields and methods defined on `Post`, just like `Answer`.

Hope this helps!

**Comment by ArtemBernatskyy** [comment]
So we can use `join` relationship without inheriting, can't we ?

**Comment by HonzaKral** [comment]
Absolutely, it is just a convenient way to define the fields and functionality that the different documents in a relationship have in common. You can also define the common fields (the `join` field at least) manually in both classes or just use a single class for both the children and parents.

Only thing that is required for things to work smoothly when using multiple classes in a single index is to specify the `_matches` class  method so that `Search` know which document to deserialize into which class.

**Comment by ArtemBernatskyy** [comment]
Thx a lot !

**Comment by ArtemBernatskyy** [comment]
Now I get it why there is a point to inherit.
Anyway, this breaks down to a single set of fields.
I'll leave this here, maybe it will help someone.

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

**Comment by teeeg** [comment]
@ArtemBernatskyy did you get a simple example working? I can't https://stackoverflow.com/questions/63510537/joins-in-elasticsearch-7-in-need-of-an-understanding

**Comment by ArtemBernatskyy** [comment]
@teeeg haven't worked with Elastic for a year, can't help you now bro (
