### ISSUE TITLE
Calling from_es with returned hits from a Search

### ISSUE THREAD

**Issue by golf-player** [elastic/elasticsearch-dsl-py#1176]
My code: 
```
MyDocType.from_es(Search(index='mydoctype').query('match', name=hit_name).execute().hits[0])
```

I see that the source for from_es uses the variable hit, so I assume it expects to be passed in a hit. This is apparently wrong since I get an attribute error; hit has no attribute `copy()`.

Seems like this is a useful usecase (at least for me), is there a recommended way of doing this sort of thing? Would you be open to a MR to add that if not?

**Comment by HonzaKral** [comment]
I am wondering why you are doing this instead of just `MyDocType.search().query('match', name=hit_name).execute().hits[0]` which will already give you an instance of `MyDocType`?

The `from_es` method is a low level method to construct the object from the raw dictionary, not the already pre-parsed `Hit` object. If you want to use it with `Hit` you will have to refer to the raw response by doing `.execute().to_dict()['hits']['hits'][0]`

Hope this helps!

**Comment by golf-player** [comment]
I didn't realize the class could be used in this way. I'll have to read the source more thoroughly. Thanks.

**Comment by ArtemBernatskyy** [comment]
@HonzaKral I'm trying to execute `MyDocType.search().query('match', name=hit_name).execute().hits[0]` but it gives me `Hit` object and not `MyDocType` object.  

But this way it works  
`some_hit = MyDocType.search().query('match', name=hit_name).execute().hits[0]`
`MyDocType(some_hit.__dict__).access_to_some_method`

Is this an expected behavior ?

**Comment by HonzaKral** [comment]
How did you define `MyDocType`? When using it like this you need to make sure it is associated with the index you are trying to access.

**Comment by ArtemBernatskyy** [comment]
CONTACT_ALIAS = 'some-alias'


    class ContactIndex(Document):
        ...

        class Index:
            name = CONTACT_ALIAS

        def save(self, **kwargs):
            self.contact_childs = CONTACT_ALIAS
            return super(ContactIndex, self).save(**kwargs)


    class MyDocType(ContactIndex):
        ...

Thx!

**Comment by HonzaKral** [comment]
The problem is that `ContactIndex` (or even `MyDocType`) is looking for index called `some-alias` but the returning documents are tagged with the name of their actual index so it doesn't match.

The `_matches` classmethod needs to be implemented in that case, as per the example (0)

Hope this helps!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py#L38-L42
