### ISSUE TITLE
RequestError while using scan

### ISSUE THREAD

**Issue by mugwump** [elastic/elasticsearch-dsl-py#1198]
I'm doing a pretty simple match_all/scan to read out all entries of an index: This works fine until I hit upon the 1001th item, then I get a 

`RequestError: RequestError(400, u'invalid_type_name_exception', u"Document mapping type name can't start with '_', found: [_search]")`

has anybody seen this before? Is this maybe a version-mismatch between the dsl-py(6.2.1) and the elastic-server(6.4.2)?!

**Comment by HonzaKral** [comment]
Can you please share the code that you are using to make the scan/scroll requests? Thank you!

**Comment by mugwump** [comment]
ok, got the reason for the error:

I specified the host together with the index to use when making the connection: 

```
connections.create_connection(hosts=["http://localhost:9201/indexName"])
```
this works __most of the time__  - but it fails, with the above mentioned error for `.scan`

When instead I specify only the host in creating the connection:
```
connections.create_connection(hosts=["http://localhost:9201/"])
```
and then specify the index in the search:

```
Search(index="indexName")
```
the `scan()` works without errors. 

I am not sure, why the initial way of specifying the host works at all, but I've been using this for month now without any issues - the only command affected by it seems to be the scan().

**Comment by HonzaKral** [comment]
That is not the correct way to specify a connection, the `Elasticsearch` class then thinks that you have an instance of elasticsearch running under the given path (some people do that when exposing elasticsearch via a reverse proxy for example) so it adds `indexName` to all API urls which is of course not valid for many APIs while it is valid for some (like `_search`) which is why it might have worked for you.

Hope this helps!
