### ISSUE TITLE
Question about top_hits

### ISSUE THREAD

**Issue by jorgelscati** [elastic/elasticsearch-dsl-py#1207]
Hello

I have this index:
```
{recorder: 1, date: "2019-06-05", model: 2}
{recorder: 1, date: "2019-06-04", model: 1}
{recorder: 1, date: "2019-06-03", model: 1}
{recorder: 1, date: "2019-06-02", model: 1}
{recorder: 1, date: "2019-06-01", model: 1}

{recorder: 2, date: "2019-06-03", model: 3}
{recorder: 2, date: "2019-06-02", model: 2}
{recorder: 2, date: "2019-06-01", model: 3}

{recorder: 3, date: "2019-06-04", model: 3}
{recorder: 3, date: "2019-06-01", model: 3}
```

I want to count how many recorders of every model exist. But only we must count **last value** of every recorder.

So, I first group by recorder and I use "top_hits" to get last valid value:
```
s = Search(index="recorderindex")
s.aggs.bucket("GROUP_BY_REC", A('terms', field="recorder", size=100000))
last_recorder_data = A('top_hits', sort=[{"date": {"order":"desc"}}], size=1)
s.aggs["GROUP_BY_REC"].bucket("LAST_RECORDER_DATA", last_recorder_data)
```
Like ElasticSearch code:
```
{
    "aggs": {
        "GROUP_BY_REC": {
            "aggs": {
                "LAST_RECORDER_DATA": {
                    "top_hits": {
                        "size": 1,
                        "sort": [
                            {
                                "datas.194": {
                                    "order": "desc"
                                }
                            }
                        ]
                    }
                }
            },
            "terms": {
                "field": "datas.178",
                "size": 100000
            }
        }
    },
    "query": {
        "match_all": {}
    }
}
```

Result:
```
{recorder: 1, date: "2019-06-05", model: 2}
{recorder: 2, date: "2019-06-03", model: 3}
{recorder: 3, date: "2019-06-04", model: 3}
```

But not, how do I apply a "terms" bucket to these results?. I expected:
```
model: 2 --> count: 1
model: 3 --> count: 2
```
... etc

**Comment by HonzaKral** [comment]
Unfortunately that is not really possible in elasticsearch and you will be better of doing this in python. The aggregations in elasticsearch work on documents and only things that can be calculated in a distributed fashion. The calculation you have in mind needs to be performed on the results of other aggregations. Those are usually done by some `pipeline` aggregations but I am not sure it can be done in this case.

Either way doing this in python (I recommend using `Counter` (0)) is straightforwards enough and will be plenty performant since only a few keys need to be considered which are, at that time, already loaded into memory from the json.

Hope this helps!


0 - https://docs.python.org/2/library/collections.html#collections.Counter

**Comment by jorgelscati** [comment]
thank you  for your answer
