### ISSUE TITLE
UpdateByQuery.params/extra doesn't work

### ISSUE THREAD

**Issue by Chernfalin** [elastic/elasticsearch-dsl-py#1218]
1 UpdateByQuery.params
my code:
ubq = UpdateByQuery(index='xxx').query("match", name="abc")
ubq = ubq.params(lable="test")
then ubq.to_dict()
output:
{'query': {'match': {'name': 'abc'}}}  ## label="test" disappeared.

2 UpdateByQuery.extra
ubq = ubq.extra(explain=True)
to_dict look fine:
{'query': {'match': {'name': 'abc'}}, 'explain': True}
rep = ubq.execute()
response:
{'took': 7,
 'timed_out': False,
 'total': 1,
 'updated': 1,
 'deleted': 0,
 'batches': 1,
 'version_conflicts': 0,
 'noops': 0,
 'retries': {'bulk': 0, 'search': 0},
 'throttled_millis': 0,
 'requests_per_second': -1.0,
 'throttled_until_millis': 0,
 'failures': []}
BUT elasticsearch nothing change except "_version".

**Comment by Chernfalin** [comment]
elasticsearch version:7.01
elasticsearch-dsl version:7.00

**Comment by HonzaKral** [comment]
1. is expected as `params` defines a query parameter which would not show in `to_dict` which only shows the body

Overall the issue is that `explain` is not a recognized parameter for `update_by_query` API (0) so no change except the version bump is actually expected behavior. What is it that you are trying to achieve?

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html
