### ISSUE TITLE
No easy way to define properties with @ (and possibly other special chars)

### ISSUE THREAD

**Issue by LordGaav** [elastic/elasticsearch-dsl-py#123]
I just ran into the issue that I could not easily use the @timestamp property, because @ is not a valid character for use in python arguments.

For instance, consider the following query and the workaround that I've employed now

```python
    s = Search(using=client, index=",".join(index))\
...
        .filter(F("range", **{"@timestamp": {"gte": frm.isoformat(), "lte": to.isoformat()}}))
```

I noticed that in https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/utils.py#L196 a special case is made that translates "__" to "." in property names. Maybe something like that should also be used for @ properties, seeing as at least @timestamp is common.

**Comment by HonzaKral** [comment]
Unfortunately that is not anything we are planning. There is really no other special character that would work instead since `@` is typically at the beginning so underscore won't work (not to mention that it's legal in field names) and anything else would also disqualify the use in a python identifier.

There will be cases where we are limited by our design, this is unfortunately one of them.
