### ISSUE TITLE
should query converted to must if minimum_should_match is not specified

### ISSUE THREAD

**Issue by candale** [elastic/elasticsearch-dsl-py#1234]
I've tried the following:
```
In [43]: a
Out[43]: Bool(filter=[Nested(path='matching_objects', query=Exists(field='matching_object.10'))])

In [44]: b
Out[44]: Bool(should=[GeoDistance(distance='30000.0km', location={'lat': 4.0, 'lon': 12.0})])

In [45]: a & b
Out[45]: Bool(filter=[Nested(path='matching_objects', query=Exists(field='matching_object.10'))], must=[GeoDistance(distance='30000.0km', location={'lat': 4.0, 'lon': 12.0})])
```
I noticed that the *should* query gets transformed into a `must` query. This is happening because  the check [here](https://github.com/elastic/elasticsearch-dsl-py/blame/master/elasticsearch_dsl/query.py#L163) is evaluate to True for the query `b`.
```
min_should_match = qx._min_should_match
# all subqueries are required
if len(qx.should) <= min_should_match:
    q.must.extend(qx.should)
```
I understand that we add the queries from *should* to *must* when `minimum_should_match` is a number above the number of queries in *should*, which means that all the *should* queries are necesary.

For a *should* query, if *minimum_should_match* is not explicitly specified, my guess is that the value should be calculated by ES. In this case, I think that `_minimum_should_match` should have a default value of `None` and only if it is an actual integer should [that](https://github.com/elastic/elasticsearch-dsl-py/blame/master/elasticsearch_dsl/query.py#L163) condition be evaluated. In the present form, it feels like the code takes a decision that the user has not necessarily agreed to.

What do you think?

**Comment by HonzaKral** [comment]
Hi, thank you for the issue, I am glad someone is curious about that logic as it is a bit complex and the more eyes on it, the better.

Right now we are detecting what the parameter would evaluate to in elasticsearch (see [0]) because otherwise we wouldn't be able to perform proper `and`/`or` logic. Once we rely on this logic in one place it makes sense to go one step further and simplify things by removing `should` in favor of `must` where equivalent.

If we treated unset `minimum_should_match` as `None` (or "unknown") we wouldn't be able to perform the simplification that allows us to produce a flatter query.

Does that answer your concerns?

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/query.py#L130

**Comment by candale** [comment]
Ahhh, I get it now. 
If the query with *should* has only one query, the default for `minimum_should_match` being 1, adding it to *must* makes sense. On the other hand, if there are two queries in *should*, I get the behavior I expected in the first place:

```
In [29]: a
Out[29]: Bool(filter=[Nested(path='matching_objects', query=Exists(field='matching_object.10'))])

In [30]: b
Out[30]: Bool(should=[GeoDistance(distance='30000.0km', location={'lat': 4.0, 'lon': 12.0}), Match(field='asdf')])

In [31]: a & b
Out[31]: Bool(filter=[Nested(path='matching_objects', query=Exists(field='matching_object.10'))], minimum_should_match=1, should=[GeoDistance(distance='30000.0km', location={'lat': 4.0, 'lon': 12.0}), Match(field='asdf')])
```

I see it now. Thanks for the clarification!
