### ISSUE TITLE
(question) reusing code when multiple indexes have same data

### ISSUE THREAD

**Issue by littlehome-eugene** [elastic/elasticsearch-dsl-py#1285]
I have review_index and product_index (review field has the same data on both index) 
```

review = {
name: 'review1',
address: "address1",
}

product = {
name: 'product1',
review: {  # same data as above
  name: 'review1',
  address: "address1",
}
}

```

a user can search review_index or product_index

say I have a code to build a Q for address field (I have many other fields)
```

def build_address_query(user_query):

  q = Q("match", address=user_query)
  return q


```
I want to reuse the code when searching for product as well, I could do something like the following

```

def build_address_query(user_query, prefix=""):

  if prefix:
    field_name = f'{prefix}.address'
  else:
    field_name = 'address'
  q = Q("match", **{field_name: user_query})
  return q
```

When calling from product search, call `build_address_query(user_query, "review")`
when calling from review search, call `build_address_query(user_query)`

I guess it works, but wonder if there's an alternative approach?

**Comment by HonzaKral** [comment]
The best approach is to have consistent naming across indices, if that is not possible you can use wildcards in queries like `multi_match` using the `fields` paramater (0). Otherwise a pure python solution like you highlighted will work as well.

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#field-boost
