### ISSUE TITLE
How can I set format for DataField()

### ISSUE THREAD

**Issue by playma** [elastic/elasticsearch-dsl-py#1296]
I want to use the format of `HH:mm` like the url below

https://www.elastic.co/guide/en/elasticsearch/reference/5.1/mapping-date-format.html

Can anyone help me?

**Comment by HonzaKral** [comment]
Hi, unfortunately at that point you will have to implement the (de)serialization yourself since the built-in `Date` field doesn't support setting custom format as there is no easy way to then deserialize the data from elasticsearch into a python `datetime` object.

To do that you can have a look at the example (0) in tests. You can also just use a `Integer` field and create a property on your `Document` subclass that will do the appropriate translation, that is probably the most efficient way.

Hope this helps!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_document.py#L49-L60

**Comment by playma** [comment]
@HonzaKral Thx
