### ISSUE TITLE
Meta attribute has underscore

### ISSUE THREAD

**Issue by MauricioRoman** [elastic/elasticsearch-dsl-py#130]
According to the example and the documentation:

for hit in response:
    print(hit.meta.score, hit.title)

Yet, in my tests, I only see the attribute '_meta'.

**Comment by HonzaKral** [comment]
Is it possible that you are using older version? If you install the library from master, does it persist?

Since the early stages of the library I only maintain one version of the docs, the Changelog (https://github.com/elastic/elasticsearch-dsl-py/blob/master/Changelog.rst) however should give you an idea when changes have been introduced and released (or that they haven't been released yet).

Sorry for the confusion.

**Comment by HonzaKral** [comment]
No response so I will assume it was the older version. If not please reopen. Thanks!
