### ISSUE TITLE
how to use RandomScore?

### ISSUE THREAD

**Issue by mortada** [elastic/elasticsearch-dsl-py#1369]
could someone point me to an example of `RandomScore`? I'd like to use random score for (seeded) random sorting, similar to this github issue: https://github.com/elastic/elasticsearch/issues/1170#issuecomment-22819670 

but I'd like to do this with `elasticsearch-dsl-py`

**Comment by brainix** [comment]
I do it like this:

    class MyDocument(Document):
        ...

        @classmethod
        def random(cls, *, seed=0, num_docs=10):
            search = cls.search(using=es_client, index='index-name')
            search = search.query(
                'function_score',
                functions=({
                    'random_score': {'seed': seed, 'field': '_seq_no'},
                }),
            )
            search = search[:num_docs]
            return search

If you want to specify a seed, then you also need to specify a field. More info on that (as well as why I chose `seq_no` for my field):
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random

Hope that helps!

**Comment by mortada** [comment]
thank you this works!

do you also know how I could incorporate `search_after` into the random sorting? basically I'd like to be able to make another call with random sorting, and not get any previously seen results using something like  

```python
some_score_or_value = ?
search = search.extra(search_after=some_score_or_value)
```

with a normal sort I could put a one-element list of the last sort value, and it'd work

**Comment by mortada** [comment]
actually I figured out a way, just have to add this:
```python
search = search.sort({"_score": {"order": "asc"}})
```

then I could use the last `sort` value of the previous call, as the `search_after` on the next call
```python
search = search.extra(search_after=last_result['sort'])
```

**Comment by biabhishek** [comment]
@brainix, could you share why you used `_seq_no ` for your field? The official [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random) only has this info:

`
A good default choice might be to use the _seq_no field, whose only drawback is that scores will change if the document is updated since update operations also update the value of the _seq_no field.
`

For my case, comparison of using a keyword field from the index vs `_seq_no` field, the `_seq_no` query with `random_score` function has much better latency when retrieved large number of documents (>10000). I wanted to understand why this happens and what is the difference between using _seq_no vs any other field in index in relation to latency.
