### ISSUE TITLE
Malformed host headers

### ISSUE THREAD

**Issue by andrewgy8** [elastic/elasticsearch-dsl-py#1530]
Hey! We have just spun up an Elastic Cloud instance and I am trying to connect from my local machine using the Elasticsearch Dsl client. 

However Im running into an issue: 

> elasticsearch.exceptions.RequestError: RequestError(400, '400 Bad Request: malformed Host header')

My connection code:

```
client = connections.create_connection(
        host='https://<namespace>.aws.found.io',
        api_key=('<key-id>', '<api-key>'),
        scheme='https',
        port=443,
    )
```
Any ideas? 

Ive tried a combination of things including changing the port, scheme, the host format, using the Elasticsearch client directly, however none of those worked.

**Comment by iamthen0ise** [comment]
@andrewgy8 

Maybe passing API credentials like described here https://www.elastic.co/guide/en/cloud/current/ec-getting-started-python.html#ec_basic_authentication_3 would be helpful?

I think it should work because `create_connection` method just pass arguments to Elasticsearch client itself https://github.com/elastic/elasticsearch-dsl-py/blob/58c02732658018333cfd5fa2f7b70d942773b0be/elasticsearch_dsl/connections.py#L78

**Comment by andrewgy8** [comment]
Yeah, I was trying to do it without the CloudID as I did not have access to it.

Perhaps the API host/port is not documented? 

Anyways, I used the CloudId and everything worked as expected.
