### ISSUE TITLE
Getting warning: client is unable to verify that the server is Elasticsearch

### ISSUE THREAD

**Issue by nrsimha** [elastic/elasticsearch-dsl-py#1542]
Hello,

I just found I am getting following warning

    elasticsearch_dsl/search.py:715: 
    ElasticsearchWarning: The client is unable to verify that the server is Elasticsearch due security privileges on the server side

Using these python modules:
    elasticsearch            7.15.1
    elasticsearch-dsl        7.4.0

And Elasticsearch version on the server is:
    elasticsearch/stable,now 7.15.1 amd64

Everything with search works fine, is there something I should do for warning to disappear?

**Comment by sethmlarson** [comment]
Great question! The warning itself is harmless, it only means that the client wasn't able to verify the Elasticsearch version and distribution.

This is done via the `.info()` API, so that API is likely returning with authorization or authentication errors. To silence the warning you'd have to add the `monitor` cluster permission to your API Key or user.
