### ISSUE TITLE
Search returns Hit objects instead of documents.

### ISSUE THREAD

**Issue by IavTavares** [elastic/elasticsearch-dsl-py#1622]
I run the following:
```
search_doc = Document.search(
        using=client, 
        index=custom_index
)

search_doc = search_doc.query("term", doc_field = f"string_{num}")

```
and then use `.scan()` I get `Hit` objects. So, something seems to be wrong...

However, when I use the ids of those hit objects:
```
all_docs = [doc.meta.id for doc in search_doc.scan()] 
for id in all_docs:
  loc = Document.get(
                  using=client, 
                   index=custom_index,
                  id = id
          )
 assert isinstance(doc, Document) # <- always true!!
```

Why is there this difference?

**Comment by sethmlarson** [comment]
Hits have additional metadata over documents. They contain information about what index, ID number, and more. Searches return Hits and scan uses search behind the scenes, this is the reason for the difference. Hope this answers your question.

**Comment by IavTavares** [comment]
I don't think your comment closes the issue Seth...
For example, usually I don't get hits on a search object, when I iterate over  the scan... I get document objects. However, if somehow I created a documented that does not comply with the index mapping (and it's not strict), the iteration over the scan will return hit objects instead of document objects... 
Also, if I redefine the _matches method of the Document object to always return True, then regardless of the document field structure, I will always get a document object, even when it doesn't comply with the mapping. 
So, I think your comment does not close this issue...

**Comment by laggardkernel** [comment]
I remember Search execute() used to return Hit and i wrote a hit_to_doc() helper to convert it to doc. But today when I'm implementing some elaticsearch features, i realize it's returning Document object. Did the package change the search result? Or I ran into some case that Document were not returned as expected before?

Update 1: sorry to bother you guys. It seems I find some clue:

- https://github.com/elastic/elasticsearch-dsl-py/issues/1143
- https://github.com/elastic/elasticsearch-dsl-py/issues/1125

**Comment by miguelgrinberg** [comment]
A plain `Search` object that is not associated with a document class will return `Hit` instances, because that's all it knows about. But when you create a `Search` object via the document, i.e. `search = MyDocument.search()`, then this instance knows what your document class is and will return search results as documents.

**Comment by laggardkernel** [comment]
@miguelgrinberg Thanks for your help. After some digging, I realized my issue was related to using an alias instead of the actual index name in the `class Index` definition.

During testing, I must have left the value as the index name and only switched it to the alias after the tests passed—before pushing the code to production. That explains why I initially saw `Document` objects returned, but later `Hit`.
