### ISSUE TITLE
Why there is no logging call?

### ISSUE THREAD

**Issue by pfk-beta** [elastic/elasticsearch-dsl-py#1678]
Hello,

I'm using elasticsearch with django and drf, and I would like to look at queries which are sent to elasticsearch server. I was thinking, that enabling logging for elasticsearch-dsl will give me quick look at it. But I need to find another way, because there are no logging calls at all. I'm just curious why there is no logging inside it

**Comment by pquentin** [comment]
Hello!

elasticsearch-dsl-py does not make queries by itself, it delegates them to https://github.com/elastic/elasticsearch-py which for version 8.x delegates them to https://github.com/elastic/elastic-transport-python/.

A simple way to get logging for all the libraries you're using is:

```python
import logging
import sys

from elasticsearch import Elasticsearch

logging.basicConfig(
    format="%(levelname)s %(name)s %(message)s",
    stream=sys.stdout,
    level=logging.DEBUG,
)

es = Elasticsearch("https://...:443", api_key="...")
es.info()
```

That's a bit coarse, because it will print DEBUG logs from urllib3 too. Setting the level to INFO will help in this simple example, but not for more complex applications. If you need more fine-grained configuration, you will have to resort to  more complex [logging configuration](https://docs.python.org/3/library/logging.config.html). Here's the configuration that Rally uses, for example: https://github.com/elastic/rally/blob/master/esrally/resources/logging.json

And finally, if you're troubleshooting a one-off issue, consider using `elastic_transport.debug_logging()`: https://elastic-transport-python.readthedocs.io/en/latest/logging.html#logging
