### ISSUE TITLE
Document use cases where mappings already exist (re Persistence)

### ISSUE THREAD

**Issue by thedeadliestcatch** [elastic/elasticsearch-dsl-py#1708]
Specifically, I would like to see some explanations about how existent mappings are handled.

Suppose I recreate my mappings per the persistence ORM-like classes. I cannot use init(0 as they already exist in the index. How does the package handle this situation?

I'm very interested in using the library, but don't want to shoot myself in the foot if I can't later on interop with existent code (for example, bootstrapping tools that parse another format and prepare the indices and mappings out of band).

The migration logic is also not well documented.

Overall, I see a lot of potential but this library seems like an afterthought.

**Comment by miguelgrinberg** [comment]
> Suppose I recreate my mappings per the persistence ORM-like classes. I cannot use init(0 as they already exist in the index. How does the package handle this situation?

If you recreated the mappings, then you would not call `init()`, since there is nothing to initialize. As long as the mappings that you created in your document class map exactly to the existing index, then you should be able to use your class just fine.

Another alternative that you have is to let the library figure out the mappings from the index itself, by calling the `load_mappings()` method. Example:

```python
class MyDocument(Document):
    class Index:
        name = 'index-name'

MyDocument._index.load_mappings()
```
