### ISSUE TITLE
Unexpected outcome when combining queries

### ISSUE THREAD

**Issue by codeasashu** [elastic/elasticsearch-dsl-py#1715]
Consider following python code:

```py
q1 = EQ("bool", should=[{"range": {"d": {"gte": 4}}}, {"term": {"c": "1"}}])  # contains 2 conditions
q2 = EQ("bool", should=[{"range": {"d": {"gte": 4}}}])  # contains only 1 condition
q3 = EQ("bool", must=[{"term": {"a": "1"}}, {"term": {"b": "1"}}])

print(q1 & q3)
# outputs: Bool(minimum_should_match=1, must=[Term(a='1'), Term(b='1')], should=[Range(d={'gte': 4}), Term(c='1')])
print(q2 & q3)
# outputs:  Bool(must=[Term(a='1'), Term(b='1'), Range(d={'gte': 4})])  which is wrong
# the output should be: Bool(must=[Term(a='1'), Term(b='1')], should=[Range(d={'gte': 4})]) 
```

Both q1 and q2 have `should` queries and doing `&` with a `must` query should append the `should`, however
doing `q2 & q3` is ignore the `should` altogther and the condition gets appended in `must`.

**Comment by honzakral** [comment]
that is expected behavior - for a `bool` query with a only a `should` clause, and no `must` the `minimum_should_match` defaults to `1`, meaning that the `range` query in `q2` is *required*. A logical AND operation with `q3` (where both `term` queries are required) results in a query where all three clauses are required.

**Comment by pquentin** [comment]
Thanks Honza, closing.
