### ISSUE TITLE
Filter records by timestamp.

### ISSUE THREAD

**Issue by justnick21** [elastic/elasticsearch-dsl-py#181]
Hello, 

I have added a MetaField for timestamp on my DocType but am having trouble filtering for it using the query: 

s.filter('range', _timestamp={'gte': datetime}) 

Do I have to include the timestamp meta field and if so is this possible through elasticsearch-dsl-py? In raw DSL i think it would look like this:

```
{
    "fields": [
       "_timestamp"
    ], 
    "query": {
        "range": {
           "_timestamp": {
              "from": 20140301101010000,    
              "to": 20140301101010999
           }
        }
    }
}
```

Thanks for any help in advance!

Nick

**Comment by brizzbane** [comment]
This is addressed in the docs:

https://github.com/elastic/elasticsearch-dsl-py/blob/master/docs/search_dsl.rst

Note:
In some cases this approach is not possible due to python's restriction on identifiers - for example if your field is called @timestamp. In that case you have to fall back to unpacking a dictionary: s.query('range', ** {'@timestamp': {'lt': 'now'}})

**Comment by justnick21** [comment]
Sorry, perhaps I wasn't clear. 

I have no problem filtering using a range filter on a field which I have indexed into elasticsearch (even if the name of the field contains characters like the @ symbol).

The problem I am having is that I cannot filter on the automatic timestamp which elasticsearch will add to each document if you add to the mapping:

```
"_timestamp" : {
   "enabled" : true,
   "store" : true
}
```

or to do the same in elasticsearch-dsl-py:

```
class DocType(DocType):
    title = String(index='not_analyzed')
    date = Date()

    class Meta:
        timestamp = MetaField(enabled=True, store=True)
```

I would expect to use:
```
s.filter('range', _timestamp={'gte': datetime})
```

However in order to filter by _timestamp you need to manually add it to the query fields which in raw dsl would be done by including:

```
"fields": [
       "_timestamp"
    ], 
```

This is what I cannot find if there is a method for doing in elasticsearch-dsl-py.

**Comment by HonzaKral** [comment]
If you use the `filter` method you are adding a filter, not a query. The search request ` Search().filter('range', _timestamp={'lte': datetime.now()})` with thus produce this json:

    {
      'query': {
        'filtered': {
          'filter': {
            'range': {
              '_timestamp': {'lte': datetime.datetime(2015, 6, 18, 16, 53, 21, 420034)}
            }
          },
          'query': {'match_all': {}}
        }
      }
    }

Which is what you want if you want to filter on `_timestamp` since filters will be much faster than queries.

For this to work though you need to have the `_timestamp` field enabled in your mappings (0) which you can do using the `DocType` class:

    from elasticsearch_dsl import DocType, MetaField
    class MyDoc(DocType):
        class Meta:
            timestamp = MetaField(enabled=True)


Hope this helps.

**Comment by HonzaKral** [comment]
Since there is no additional questions/information I am closing this ticket
