### ISSUE TITLE
Possibility to specify unbounded number of results

### ISSUE THREAD

**Issue by hakanw** [elastic/elasticsearch-dsl-py#182]
I can't seem to find out a way to specify unlimited number of results. Since slicing is the only thing documented, I tried for example:

``MyThing.search().query(...)[:]``

Is it possible?

**Comment by justnick21** [comment]
You have to set the _params 'size' key to whatever you want it to be. 

So:

```
search = MyThing.search()
search._params['size'] = 2147483639
```

I used 2147483639 because this is the maximum results size (0 should set size to max but doesnt?)

**Comment by HonzaKral** [comment]
Unfortunately tehre is no functionality like this in elasticsearch itself. If you want to retrieve all your documents (or all documents matching a query) use the `scan` method on the `Search` object. This uses the scroll/scan mechanics in elasticsearch to get you all the results in optimized fashion.

The optimizations involved also mean that the results won't be sorted according to the score though (since that can be VERY expensive). If you absolutely need to have documents sorted you can pass in a parameter `preserve_order` (via calling `.params(preserve_orde=True)` before calling `scan`) - but be careful since this can be a very expensive operation for your cluster.

Hope this helps
