### ISSUE TITLE
Add items and iteritems methods to the AttrDict class

### ISSUE THREAD

**Issue by sauramirez** [elastic/elasticsearch-dsl-py#187]
Enhancement: Instead of having to call .to_dict().items() we can just call .items() from the AttrDict instance.

**Comment by HonzaKral** [comment]
I am not sure about this - I don't want to clutter the namespace of the `AttrDict` class because it is used in many cases where `items` for example might be a valid key - like an `Inventory` class (derived from `DocType`) or something.

I also feel that it might be a slippery slope leading to people wanting to (with reason) all of the `dict` methods, which is imho too much: `clear`, `copy`, `fromkeys`, `get`, `items`, `keys`, `pop`, `popitem`, `setdefault`, `update` and `values`

Currently I am actually even considering removing the `get` method for the very same reason, leaving the `to_dict` an only public member of that class.

What do you think? Is it more surprising to not be able to do `iteritems` or being limited in your choice of keys (or access to those conflicting fields)?

Thanks!

**Comment by sauramirez** [comment]
Right I do think the namespace for AttrDict shouldn't be cluttered, it was just confusing to have something called a dictionary that doesn't really implement all of the dictionary methods.

**Comment by HonzaKral** [comment]
Since `to_dict` is very cheap I am inclined to just document the behavior and skip these methods, leaving us with just the `__magic__` ones like `__getattr__`, `__iter__` and `__getitem__`.

**Comment by sauramirez** [comment]
Yes, to_dict should be fine. Thanks for the response, I think you can close this.

**Comment by HonzaKral** [comment]
Thanks for the discussion and raising this issue!
