### ISSUE TITLE
Unexpected keyword argument "meta"

### ISSUE THREAD

**Issue by Allaoua9** [elastic/elasticsearch-dsl-py#1955]
```
class Step(Document):
    threadId: str = mapped_field(Keyword(required=True))
    parentId: str | None = mapped_field(Keyword())
    type: str = mapped_field(Keyword(required=True))

step = Step(meta={"id": 1}, threadId="1", parentId="1", type="1") # Unexpected keyword argument "meta" for "Step"mypy[call-arg]
```

Passing meta or any undeclared attributes in the constructor causes a MyPy Call-arg error.

**Comment by miguelgrinberg** [comment]
This is because `meta` is not defined in your `Step` class. The typing for the `Document` constructors is based on dataclasses, so unfortunately any arguments that you pass have to be explicitly defined in the class. Here is a section of one of our example apps, showing how to do it:

https://github.com/elastic/elasticsearch-dsl-py/blob/5a2cc863fb65f368edbe2763106900308e165b66/examples/alias_migration.py#L50-L59

In your case you'd want to add something like:

```python
    if TYPE_CHECKING:
        meta: Dict[str, Any]
```

**Comment by Allaoua9** [comment]
Thanks for the answer. I did not know you could pass `_id`, wonderful !

I think this should be added to the documentation https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html

**Comment by Allaoua9** [comment]
I went with the _id solution. my Step class, inherits from a base class called MigratableDocument(AsyncDocument) : 

```python
class MigratableDocument(AsyncDocument):
    if TYPE_CHECKING:
        _id: str | None = mapped_field(default=None, kw_only=True)

    @property  # type: ignore[no-redef]
    def _id(self) -> str | None:
        return self.meta.id if "id" in self.meta else None
```
I also added a getter for prop `_id` for simplicity as we cannot access _id with `doc._id` even though we can pass it to the constructor.

Now i can pass _id without raising a mypy call-arg error :

```
step = Step(_id="1", threadId="1", parentId="1", type="1")
print(step._id) # This will call the declared property getter for _id 
```

Setting `kw_only=True` is necessary to avoid "Attributes without a default cannot follow attributes with one" error.
