### ISSUE TITLE
Meta fields for Search>Result objects

### ISSUE THREAD

**Issue by 3lnc** [elastic/elasticsearch-dsl-py#196]
Seems that metadata does not propagates from `meta` to access it via `._field` for generic search
```python
>>> class model(DocType):
>>>     ...
>>> model().save()

>>> model.search().execute()[0].meta.id
{id}
>>> model.search().execute()[0]._id
{id}
>>> Search(index='index').execute()[0].meta.id
{id}
>>> Search(index='index').execute()[0]._id
AttributeError: 'Result' object has no attribute '_id'
```

**Comment by HonzaKral** [comment]
Yes, that is true, it only works for `DocType`s. The `Result` class is much much simpler as to avoid additional overhead that doesn't bring much.

**Comment by 3lnc** [comment]
Mb, but for me it seems like a bit inconsistent. Sometimes there's need to perform search against multiple indexes/doctypes, results _seems_ the same as for models `.search`, but interface for meta differs, which is forcing to get meta params via `.meta.field` to write polymorphic code.

**Comment by HonzaKral** [comment]
Yes, if you want consistency and safety, just use the `.meta`, that's why it is there. `DocType` simply support more. If you know you are only working with `DocType` classes then you have a choice.

I don't see how this is different or inconsistent - there is simply a more specialized, richer API that you can use. It has some downsides (like the need to create the `DocType` class, limiting the usable namespace, slight performance hits, ...).

This is a very common pattern in APIs where you have lower-level objects (`Result`) and then objects bulding on top of those to add more functionality (`DocType`).

**Comment by 3lnc** [comment]
Fine then, as it is as it meant to be.
