### ISSUE TITLE
ES 2.0 Beta - Add Query vs Filter context support

### ISSUE THREAD

**Issue by reflection** [elastic/elasticsearch-dsl-py#248]
If you look at the 2.0 docs, anything in the 'filter' key in the 'query' hash is filter context:
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-filter-context.html

So all queries with filters should look something like below:

query: {
   filter: { ... }
}

**Comment by HonzaKral** [comment]
The docs only mention that there are different ways how queries are interpretted, the only new additions are the `filter` branch of a `bool` query (added in d3b4f0163147b67baa9f0acb1c1a9a7031f078e5) and the removal of filters in favor of just queries.

I have added the `filter` parameter since it is backwards compatible, but this library is still intended for use with Elasticsearch 1.x. I will be creating a branch soon for 2.0 features that will reflect these changes, as well as #247.

Hope this helps

**Comment by reflection** [comment]
I completely agree with a new branch for 2.0 features.  Thanks!
