### ISSUE TITLE
Upsert in `update`

### ISSUE THREAD

**Issue by twall** [elastic/elasticsearch-dsl-py#250]
Would it make sense to tweak `DocType.update()` to perform an upsert if the item doesn't already exist (at https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/document.py#L227)?

        meta = es.update(
            index=self._get_index(index),
            doc_type=self._doc_type.name,
            body={'doc': fields, 'doc_as_upsert': True, 'detect_noop': True},
            **doc_meta
        )

**Comment by HonzaKral** [comment]
I am wondering why you'd then use `update` instead of just `save` when upsert behavior is what you want?

**Comment by twall** [comment]
Examining the code for `save` didn't show me any upsert options, but perhaps I was looking at an outdated version?

**Comment by HonzaKral** [comment]
No, there is no explicit upsert, but it behaves in a similar way - if the document exists it will get overridden, otherwise it will get created.

**Comment by dboczek** [comment]
Example where upsert is convenient.

Lets assume I have simple document.

def Document(DocType):
    text = Text()
    read_counter = Integer()

Now consider that there is two separate programs that use this Document.
One is indexing Documents without touching counter and other updates only counter.
The later can assume that document always exist so I can use `document.update(read_counter=reads)`.
I can't do the same for first because what I need is to index document if it does not exist or update if it exists unfortunately document.save() will overwrite whole document thus read_counter is lost in process.

I know I could get document first to check if it exists but the whole point of the update API in ES is to avoid that.

> Note, this operation still means full reindex of the document, it just removes some network roundtrips and reduces chances of version conflicts between the get and the index. 
Although it says full reindex it reads current document merges it with received one and then saves so it does not loose data that was there.

Otherwise why implementing update at all? I can always get instance update some fields and save whole document.

**Comment by xkungfu** [comment]
so, how on earth update a doc like upsert?
did you find a solution at last?
is there a document tell us how to implement?

thanks!
