### ISSUE TITLE
from elasticsearch_dsl import Long gives unresolved import: Integer in Eclipse

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#282]
Why if I am using this library and I use eclipse when I write:

from elasticsearch_dsl import Integer

or 

from elasticsearch_dsl import Long

gives me unresolved import: Integer

although I have correctly installed and when I execute I dont have any error.

**Comment by HonzaKral** [comment]
This is most likely due to the dynamic nature of the library where it generates a lot of these classes in import time.

There is unfortunately nothing we can do here, aside from generating a bunch of code manually and keep it in the files instead of doing it at import time. This is definitely an option for the future, but currently there are other priorities unfortunately.

**Comment by juandasgandaras** [comment]
Ok thanks for your help.
