### ISSUE TITLE
How to specify `request_timeout`?

### ISSUE THREAD

**Issue by ei-grad** [elastic/elasticsearch-dsl-py#301]

**Comment by HonzaKral** [comment]
You can provide `params` to the `Search` object: `s = Search().params(request_timeout=5)`

**Comment by johnraz** [comment]
Can't we do that globally ? (sorry to comment on a close issue, but I'm really wondering)

**Comment by HonzaKral** [comment]
of course, when configuring the connection to elasticsearch you can specify any arguments to `Elasticsearch`, including `timeout`.

**Comment by hvdklauw** [comment]
Was just looking for this and I'm thinking, isn't the timeout on the ElasticSearch class the connection timeout?, and not the request_timeout?

**Comment by HonzaKral** [comment]
@hvdklauw  `request_timeout` can be passed to any API call to override the global default, which is called just `timeout` when passing it to `Elasticsearch.__init__`.

The unfortunate difference in names is caused by some elasticsearch APIs that already accepted parameter `timeout` which refers to something else. You can find some more on this at [0]

0 - https://elasticsearch-py.readthedocs.io/en/master/api.html#timeout
