### ISSUE TITLE
Possible to include icu_tokenizer in analyzer?

### ISSUE THREAD

**Issue by pkphlam** [elastic/elasticsearch-dsl-py#328]
Hi, 

Is it possible to include the icu_tokenizer (https://www.elastic.co/guide/en/elasticsearch/guide/current/icu-tokenizer.html) and icu_folding token filter in an analyzer with elasticsearch_dsl?

```
doc_analyzer = analyzer('doc_analyzer', tokenizer='icu_tokenizer', filter=['lowercase'])

UnknownDslObject: DSL class `icu_tokenizer` does not exist in tokenizer.
```

**Comment by HonzaKral** [comment]
I am hesitant to include those analyzers since they are not shipped with elasticsearch by default. Currently the fix would be to define them yourself:

    class ICUTokenizer(Tokenizer):
        name = 'ico_tokenizer'

and then your code will work.

Alternatively I have been thinking, since this issue keep popping up, to completely remove the list of tokenizers from the library and just rely on the users - if you supply a string we will just use it verbatim, only if you define your own analyzer will we try and do something with it.

What do people think?

**Comment by pkphlam** [comment]
I think it would be good to allow some way to use analyzers not shipped by elasticsearch by default.

On the code (and also referencing issue #264), what's the proper way to define the custom tokenizer?

I've tried various options:
```
from elasticsearch_dsl.analysis import Tokenizer
class ICUTokenizer(Tokenizer):
    name = 'icu_tokenizer'

doc_analyzer = analyzer('doc_analyzer', tokenizer=tokenizer('icu_tokenizer'), filter=['lowercase'])
doc_analyzer = analyzer('doc_analyzer', tokenizer='icu_tokenizer', filter=['lowercase'])
doc_analyzer = analyzer('doc_analyzer', tokenizer=ICUTokenizer(), filter=['lowercase'])
doc_analyzer = analyzer('doc_analyzer', tokenizer=tokenizer('icu', 'icu_tokenizer'), filter=['lowercase'])
```
and I keep getting the error
```
UnknownDslObject: DSL class `custom` does not exist in tokenizer.
```

**Comment by HonzaKral** [comment]
I just pushed to master a change commit 46067d8 that stops whitelisting analyzers and just assumes that if you pass a string the analysis is correctly defined in ES

That should help
