### ISSUE TITLE
GEO Search

### ISSUE THREAD

**Issue by dco5** [elastic/elasticsearch-dsl-py#340]
Can elasticsearch-dsl use Geolocation on the search?

Is there an example on how to use it?

**Comment by HonzaKral** [comment]
You can use any of the geo queries supported by elasticsearch (0) by using it in a search. For example the example geo distance query from (1) would look like:
```
s = Search()
# use filter instead of query since we don't care about scoring here
s = s.filter('geo_distance', distance='200km', pin__location={'lat': 40, 'lon': -70})
```

Hope this helps,

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html
1 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html

**Comment by dco5** [comment]
@HonzaKral This is perfect!! Thank you so much!

**Comment by levylll** [comment]
@HonzaKral excuse me, could I sort the result by the distance?

**Comment by levylll** [comment]
@HonzaKral but how could I get the result distance?

**Comment by levylll** [comment]
There is a field called sort (like this --  "sort": [4754.365530479743]) is original response , but when I use the es_dsl, I can not get this field.  Could you help me please?

**Comment by HonzaKral** [comment]
@levylll The `sort` attribute is available as `hit.meta.sort` along with all the other metadata fields like type and index.

**Comment by levylll** [comment]
@HonzaKral Great! Thank you very much. Would you please update the package [elasticsearch-dsl](https://pypi.python.org/pypi/elasticsearch-dsl)

**Comment by Brechard** [comment]
@HonzaKral could you explain further how to use the sort to obtain the distance? When I do this:

`ItemDocument.search().filter(Q('geo_distance', distance=f'{distance}km', coordinates=[float(params['longitude']), float(params['latitude'])])).sort('distance').execute()`

I get the error: 

`{RequestError}RequestError(400, 'search_phase_execution_exception', 'No mapping found for [distance] in order to sort on')`
