### ISSUE TITLE
Custom Analyzer in ES DSL Aggregation Query

### ISSUE THREAD

**Issue by Erstwild** [elastic/elasticsearch-dsl-py#354]
Is it possible to use a custom analyzer in an ES DSL aggregation query?  I have a field that is a comma separated string that I would like to tokenize with a custom analyzer/aggregate (value_count)/and then sort.

**Comment by HonzaKral** [comment]
It is absolutely possible to have a cuystom analyzer, see the `analysis` chapter in the docs: http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#analysis

It seems like a better solution though to pre-parse this and actually store the field as a list with multiple values, especially if you want to aggregate on such field, since then you will be able to leave it as not_analyzed and use doc_values which is more efficient.

Hope this helps.

**Comment by HonzaKral** [comment]
There has been no new information so I assume the issue is resolved, please feel free to reopen with more information. Thanks!
