### ISSUE TITLE
"or" statement

### ISSUE THREAD

**Issue by patrick-bark** [elastic/elasticsearch-dsl-py#358]
Hey, I am wondering if there is anyway to make an `or` statement. It seems as thought the `|` operator only produces a `should` statement, when I am looking for something more along the lines of:
`term:Myterm AND (loc=myloc OR loc=anotherloc)`

This seems like a simple function, I found a stack overflow question on it, but the only answer appears to have methods no longer available in the API:
```
s = Search(using=client,
           index="my_index"
    ).filter(
        "term", status=PUBLISHED
    ).filter(
        "or", [F("range", start_publication={"lte": now}, ),
               F("missing", field="start_publication")]
    ).filter(
        "or", [F("range", end_publication={"gte": now}, ),
               F("missing", field="end_publication")]
    )
```
The `F` option is apparently deprecated. Any ideas on how to do this now? Thanks

**Comment by grapemix** [comment]
+1

We used to have F in version 0.X. So we can do something like this:

f = F("term", testField="example")
f = f | F("term", testField="example2")

programatically_created_filters = []
programatically_created_filters.append(f)
programatically_created_filters.append(F("geo_distance", loc=somve_var, distance="10mi"))

Search.filter(F('and', programatically_created_filters))


After upgrading, my app is broken immediately and the problem is not mentioned in any doc. Google and stack overflow also had no luck. 

Any suggestions will be welcome. Thanks.

**Comment by HonzaKral** [comment]
@patrick-bark: Instead of `F` you just use `Q` on 2.x version. I would also recommend using `bool` with `should` instead of `or` filter/query. You can even use the `|` operator to construct such queries. Overall this would look like:
```
is_published = Q('term', status=PUBLISHED)
is_started = Q('range', start_publication={'lte': 'now'}) | Q('missing', field='start_publication')
not_ended = Q('range', end_publication={'gte': 'now'}) | Q('missing', field='end_publication')

s = Search(...).filter(is_published).filter(is_started).filter(not_ended)
```

**Comment by HonzaKral** [comment]
@grapemix 
Filters have been deprecated, if yu just change to using `Q` instead of `F` it should work. However I would also recommend switching to `bool` from `and`, it is more performant and recommended - `and` query is being deprecated. The way to transcribe your code would be simply:
```
s = Search()
for f in programatically_created_filters:
    s = s.filter(f)
```
or, alternatively, you can just create the bool query yourself:
```
s = Search().query('bool', filter=programatically_created_filters)
```

Hope this helps

**Comment by patrick-bark** [comment]
Hey @HonzaKral from what I understand `should` is not the same function as `or` and it seems that there are certain queries that require `or`. I seem unable to use `or` with the `Q` function. Any ideas here? Can I just pass a query string in any way?

**Comment by HonzaKral** [comment]
@patrick-bark `should` with a list of queries have exactly the same semantics as `or`. That is also the reason why, since 2.0 `or` is deprecated in elasticsearch.

**Comment by patrick-bark** [comment]
Ok interesting, I must be doing something wrong here. Thanks for the help

**Comment by patrick-bark** [comment]
One last question, is there a way to implement the `minimum_should_match`, with the `should` statement?

**Comment by HonzaKral** [comment]
When `bool` is used in a filter context (https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-filter-context.html) then `minimum_should_match` is always 1

**Comment by grapemix** [comment]
Thanks for your quick response and hard work for this package. My app is fine now after applying your suggestions.

**Comment by patrick-bark** [comment]
Mine as well, you all do good work. Thanks
