### ISSUE TITLE
How to use DSL to achieve this query

### ISSUE THREAD

**Issue by shejianmin** [elastic/elasticsearch-dsl-py#367]
My index document like this
{"start_time":"2016-02-24T15:03:25", "end_time":"2016-03-13T15:03:25", "field_1": "test1", "field_2": "test2"}

Now I want to implement the following query：
Depending on whether the current time is in the `start_time` and `end_time` search on the different fields 
If true, query on `field_1` , and if not query on `field_2`

How to write，Thanks

**Comment by HonzaKral** [comment]
This should do the trick:
```
is_current = Q('range', start_date={'lte': 'now'}) & Q('range', end_date={'gte': 'now'})
current_q = is_current & Q('match', field_1='test1')
not_current_q = ~is_current & Q('match', field_2='test1')

s = Search().query(current_q | not_current_q)
```

**Comment by shejianmin** [comment]
Thank for your help, I think I get it.

**Comment by alejoar** [comment]
@shejianmin not sure if this would be an optimal solution (probably not) but you could simply pass both fields to your script as parameters and then do simple logic in the script to return the appropriate field.

Having said that, that probably doesn't even make sense if you won't process the field in any way; you would be returning a duplicate field. Just access the field you need straight from the document.

**Comment by HonzaKral** [comment]
You can track which query has matched using named queries (0), but you cannot access those in your script fields. What I would recommend is, instead of a script field, provide a method on your `DocType` to return that value. Especially since `is_current` is a check that can be done in python very easily and does not rely on any advanced matching in elasticsearch.

Hope this helps

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html

**Comment by shejianmin** [comment]
thanks
