### ISSUE TITLE
Filtering with forward slash in term

### ISSUE THREAD

**Issue by patrick-bark** [elastic/elasticsearch-dsl-py#374]
Hey, I am trying to form a query in which the term is simply `/` , I have tried escaping to no avail. Have tried using both query and filter, but neither are returning the results I am looking for. From what I have read this is because it is analyzing the field and splitting the values. According to [stack overflow](http://stackoverflow.com/questions/31442499/escaping-slash-in-elasticsearch) you need to use `fquery` with match `by_line` but I don't see anyway of doing that in the docs.

My basic query looks like:
```
is_host = Q('term', container_Name="/")

resp = Search(index='cadvisor').using(client).filter(is_host)
```

Any ideas here? Thanks

**Comment by HonzaKral** [comment]
Hi, the query, as you have it, is absolutely fine. The problem is elsewhere - in your mappings.

Could you please share you mapping definition for this document? My guess would be that `container_Name` is an analyzed field - meaning it's not the actual value of the field that is in the index but instead a result of the analysis process (see the analyze API (0) to see what that does to your input). By default (standard analyzer) this will strip out any non-text characters so your filter won't match anything.

If `container_name` is a value that you want to filter on (using exact matches) define it in mappings as `{"type": "string", "index": "not_analyzed"}`. If you need both full text search and exact filtering you can use multi fields (1) to define multiple different mappings for a single field.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html
1 - https://www.elastic.co/guide/en/elasticsearch/reference/2.2/multi-fields.html

**Comment by patrick-bark** [comment]
You are totally correct, my current mapping is:
`'container_Name': {'type': 'string'}`

So, is there an easy way to change just this field? Or better yet, prevent automatically analyzing fields in the future?

**Comment by HonzaKral** [comment]
Unfortunately mappings cannot be changed since all of this happens at index time and there is no way to update the index structure. You need to delete the index and create a new one with correct mappings. If you want to make sure these mappings are used as default you can use index templates (0) which are essentially generic settings that will be applied to any index as created. Inside such template you can then use dynamic mappings (1) to controll created mappings in the same way.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/2.2/indices-templates.html
1 - https://www.elastic.co/guide/en/elasticsearch/reference/2.2/default-mapping.html

**Comment by patrick-bark** [comment]
Sounds good, thanks for the help and resources

**Comment by HonzaKral** [comment]
happy to be of help
