### ISSUE TITLE
Fields starting with underscore end up in meta

### ISSUE THREAD

**Issue by armisael** [elastic/elasticsearch-dsl-py#400]
Hi everybody,

In our ES index we mark some private fields by prefixing them with an underscore; they are intended to be "maintenance" fields, and we use this "trick" to make this clear.

When writing a query to ES through the `elasticsearch-dsl-py` though, they do not appear on the returned items; after a bit of struggling we discovered they are actually stored in `item.meta`, so that (for example) a field called `_show` can be retrieved with `item.meta.show` instead of `item._show`.

Is this intended?

I would expect all fields in the `_source` of the document to appear on the item itself, regardless of their name.

Thanks

**Comment by HonzaKral** [comment]
Hi,

this is an unintended side effect of how we work with meta fields - currently, when instantiating a `DocType` subclass we just pass all the values into its `__init__` as kwargs. The `__init__` then separates out the meta fields and puts them into a separate `meta` dictionary. This is done so that people don't have to specify the rather awkward `MyDoc(meta={'id': 42})` and can just say `MyDoc(_id=42)`.

To avoid dependency on ES versions we coded this just by looking for an underscore at the beginning of a field.

There are 2 ways to fix this:
1. hard-code the name of all possible meta fields (`_score`, '_id', '_index', ...) and ignore others
2. don't allow this shortcut when constructing an instance, or at least do that when constructing an object ourselves (`get` or `search`).

What do you think?

Thanks for the report!

**Comment by armisael** [comment]
Thank you for the quick reply.

If the list of possible meta fields is known and limited (as I believe it is) I would go for the first solution; the second solution would force people to migrate their code to avoid the shortcut. While both ways are not backward compatible, I expect more people to complain about 2, while about 1 most likely nobody even noticed anything was wrong in the first place.
