### ISSUE TITLE
[feature] add highlighting_opts to faceted search

### ISSUE THREAD

**Issue by arthurlogilab** [elastic/elasticsearch-dsl-py#407]
A read through faceted_search doesn't seem to show any way to add highlighting options like we can on a standard search (exept by writing our own highlight method).

**Comment by HonzaKral** [comment]
I would definitely recommend overriding the highlight method since this is a very simple method. Alternatively you can override the `search` method that constructs the `Search` object and do it there:
```
def search(self):
    s = super(...).search()
    return s.highlight_options(my='settings')
```
I understand your use case but I'd prefer not to introduce all the possible options from `Search` in `facetedSearch` - instead I hope we made it easy to override certain methods and get access directly to the `Search` object being generated/used to allow for any modifications. Do you think that makes sense?

Thank you!

**Comment by arthurlogilab** [comment]
@HonzaKral ok, it does make sense, maybe this can be mentionned in the documentation so the next person doesn't try to find the equivalent options like me ?
