### ISSUE TITLE
Passing field name as string in filter

### ISSUE THREAD

**Issue by pkphlam** [elastic/elasticsearch-dsl-py#413]
Suppose I want to pass a range filter on an ES field named "date". The code would be something like:

`Search(using=es).index(index_name).doc_type(my_doc_type).query('match_all').filter('range', date={'gte': '2014-01-01})`

Is there a way I can pass the field name (date) as a string rather than hardcoded into the argument? I want to code it such that if my field name changes, I can just pass a string rather than changing the code itself. Something like:

```
mydatefield = 'date'
Search(using=es).index(index_name).doc_type(my_doc_type).query('match_all').filter('range', mydatefield={'gte': '2014-01-01})
```

**Comment by brainix** [comment]
Hello!

In my opinion, this is more of a Python question rather than an `elasticsearch-dsl-py` question.  I believe that you can achieve what you want like this:

```
mydatefield = 'date'
Search(using=es).index(index_name).doc_type(my_doc_type).query('match_all').filter('range', **{mydatefield: {'gte': '2014-01-01}})
```

For more information, see: https://docs.python.org/2/tutorial/controlflow.html#unpacking-argument-lists

I hope that this helps, and good luck!

**Comment by HonzaKral** [comment]
It is exactly as @brainix said, use python's capabilities. Thanks @brainix 

In the long term we are trying to audit the elasticsearch dsl to find these issues and change them right at the source in elasticsearch itself.
