### ISSUE TITLE
ConnectionTimeout when we have more more than one host in the connection configuration

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#438]
In reference to the #256   issue

Another question about this fail. 

If I have this configuration:

 `es = Elasticsearch(cluster,timeout=10,sniff_on_start=True, sniff_on_connection_fail=True, sniffer_timeout=60,sniff_timeout=10,max_retries=10)`

where cluster is defined in this form:

`cluster = ['bc10-03:9200','bc10-05:9200','bc10-07:9200']`

and then why does this error:

`ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'bc10-05', port=9200): Read timed out. (read timeout=40))
`
if there are more host to connect??

Thanks in advance

**Comment by HonzaKral** [comment]
Currently we don't retry on timeouts by default since it can lead to some unintedned consequences - if a `bulk` request times out and we retry we end up with the documents indexed twice.

If you wish to retry on timeout as well you can enable that by passing in `retry_on_timeout=True`.

Hope this helps

**Comment by HonzaKral** [comment]
Closing this issue snce the question is answered and also relates more to the `elasticsearch-py` than the `elasticsearch-dsl` package.
