### ISSUE TITLE
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info) elasticsearch.exceptions.TransportError: TransportError 500, u'index_failed_engine_exception'

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#441]
I am not able to understand why this error happens:

```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(500, u'index_failed_engine_exception', u'Index failed for [last_time_metric_check_out#oid:asset:my_metric.used]')

```
when I save a document

Thanks in advance

**Comment by juandasgandaras** [comment]
Ok I will try it and when I will have this made I will update this issue

**Comment by juandasgandaras** [comment]
I have tried this and I found this error:

`{u'status': 500, u'error': {u'index': u'my_index', u'root_cause': [{u'index': u'my_index', u'reason': u'Index failed for [customer_history#oid:customer:2]', u'type': u'index_failed_engine_exception', u'shard': u'2'}], u'caused_by': {u'reason': u'/tmp/elasticsearch/data/elasticsearch_dev/nodes/0/indices/gompute_history_ldap_odin/2/index/write.lock', u'type': u'no_such_file_exception'}, u'shard': u'2', u'reason': u'Index failed for [customer_history#oid:customer:2]', u'type': u'index_failed_engine_exception'}}`

What could be the error?

Thanks in advance

**Comment by HonzaKral** [comment]
This is an internal error indicating that something went wrong with your elasticsearch cluster. One shard cannot find the write lock or create it. Unfortunately there isn't much more I can tell without further details. I recommend you ask how this may happen in the forums at discuss.elastic.co

Closing this issue since it has no connection to python but is instead an internal elasticsearch error.
