### ISSUE TITLE
not possible to use string format to specify sorting by "_score" asc

### ISSUE THREAD

**Issue by nanshu** [elastic/elasticsearch-dsl-py#458]
As the default sorting direction for "_score" is desc, there is no difference between the results from `s.sort('_score')` and `s.sort('-_score')`, where `s = Search()`.

**Comment by HonzaKral** [comment]
Hm, this is tricky because it is the behavior of elasticsearch itself. If we behave "properly" here, interpretting `_source` as ascending order or have a special case for `_source` it might be confusing. What do you think?

Currently the workaround is to just be explicit and not the the string format.

Thanks!

**Comment by egens** [comment]
Got this error too. I thought that the lib corresponds to elasticsearch special case as it is described [in docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_order).

So my word for adding special case to [the logic](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L487-L490).

**Comment by HonzaKral** [comment]
Thank you for the feedback, and sorry for the delay. in 1558205 we restricted the use of `-_score`
