### ISSUE TITLE
Nest-within-nest custom mapping class times out

### ISSUE THREAD

**Issue by dterg** [elastic/elasticsearch-dsl-py#486]
I've been following the persistence doc to populate a local ES with my custom (nest-within-nest) mapping:

```
    class Article(DocType):
        title = String()
        comments = Nested(
            properties={
                'comment_id': String(),
                'words': Nested(
                    properties={
                        'dep': String(),
                        'head': String(),
                    }
                ),
            }
     )

    class Meta:
        index='processed_data'

    def save(self, ** kwargs):
        return super(Article, self).save(** kwargs)
```

My data is in json files which have the same structure as the mappings. Ideally I want to bulk upload these, but for now am instantiating the `Article`class, and then populating each of the fields:

```
    for i, iFile in enumerate(jsonlist):
       i+=1
       with open(iFile, 'r') as jsonFile:
           jsonDoc = json.load(jsonFile)

       Article.init()
       docpost = Article(title=jsonDoc['title'],
                   comments=jsonDoc['words'],
                   words=jsonDoc['words'])

       docpost.meta.id = i
       docpost.save()
```

For some reason Article.init() times outs, even after setting the timeout to 40 in the connection.

`elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=40))`

This is independent of my data size (since this happens at the instantiation level), so am assuming this is because of my custom mapping which seems sound to me. Could this be because of the nest-within-nest mapping that I'm doing?

**Comment by HonzaKral** [comment]
I personally cannot see how this would be caused by the `nested` fields - I have used nested fields like this before with no issues.

What I do see, however, is that you are calling `Article.init()` before loading each document which is not recommended - `init()` should only be called once as it is the equivalent of creating a database schema.

Also you really shouldn't use `.save()` method to load documents one by one (unless you rely on custom logic you put in there) and should instead use the `bulk` helper from `elasticsearch-py` (pass in an iterator of `doc.to_dict(True)`)

Hope this helps!

**Comment by dterg** [comment]
I have since modified the script but thanks for the tips! The issue with the connection timeout disappear after I upgraded to elasticsearch 5.0.0 (even when using the same script originally posted) so all's good :) Thanks again.
