### ISSUE TITLE
Unittests

### ISSUE THREAD

**Issue by matdrapeau** [elastic/elasticsearch-dsl-py#491]
How would you suggest to run unittests that are using ES-DSL?
If I would like to use another index, object meta couldn't be changed at runtime.

thanks

**Comment by HonzaKral** [comment]
Depends on what is the logic that you are trying to test. Would you have some more concrete examples?

**Comment by matdrapeau** [comment]
Create obj into temp index, and destroy this index after.
I just don't want to garbage "production" data if a problem occurs.
But obj are already implemented using metaclasses

**Comment by HonzaKral** [comment]
First of all please never run tests on production system, no matter ho well you think your tests and production data are isolated. It is dangerous exactly because you run tests to prove your system correct - before tests are run there is no way to say that the code won't just destroy everything in site.

Also what is this test trying to achieve? This sounds like a test `elasticsearch-dsl` should be running (and indeed it is) so there is no reason for you to have the same test in your application. If you want to have an integration test to confirm that your code communicates well with `elasticsearch-dsl`, then that's another matter. But again please never try this on production system.

What I would recommend is to have a bunch of unit tests for your classes, especially when overriding or enhancing inherited methods, that don't even communicate with elasticsearch:
```
article = Article(publish_date=now()+timedelta(days=1))
assert not article.is_published()
```

For other tests you can use the `TestCase` from elasticsearch-py: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/test.py#L39 **This test case will delete all the data in your cluster! Never run against production!**

**Comment by HonzaKral** [comment]
Closing this issue since it was resolved

**Comment by matdrapeau** [comment]
@HonzaKral Thanks for the answers...
When I was saying "production" data I wasn't referring to a production environment with live data but a DEV environment already containing data.
As an example, when unit testing sqlalchemy app, you can easily point your tests to another connection and then insert test fixtures in a silo database.
I am trying to mimic this behavior with es-dsl.

Given this object:
```
class User(DocType):
	username = String()
	password = String()

	class Meta:
		index = 'user'
```
How would you suggest to unit test `User` fixtures without conflicting with data already there in my DEV environment? Since the index is provided in the object definition it makes impossible to store insert fixtures in another index.

**Comment by HonzaKral** [comment]
You can always override the `index` explicitly but really what you want to be doing is having a different environment for dev and for testing. Otherwise, by definition, you will be testing different things than what you will be running in production because of all these overrides.

There is no substitution for separate environments.

If you still want to do it, then just change the index: `User._doc_type.index = 'not-user'`

**Comment by matdrapeau** [comment]
@HonzaKral thanks again for your prompt response.
If there is a parent relationship with the User object, how can you deal with that in test mode?

```
class Post(DocType):
	content = String()

	class Meta:
		index = 'post'
		parent = MetaField(type='user')

```

During test setup, I am trying to defer the parent to the `not-user` index as such: `Post._doc_type.parent = 'not-user'`but that gives me a `AttributeError: can't set attribute`

How do you suggest to fix that?

**Comment by HonzaKral** [comment]
This is exactly the reason why I strongly encourage you to use separate environment for testing. Without such you will keep running into issues such as these. **Please invest the time to have a separate environment for tests, without it you have no guarantees and running tests can impact your other environments.**

If you still don't want to do that I would suggest you make the index name a parameter in your configuration and the provide a different configuration in your tests.
