### ISSUE TITLE
Implement items() method in utils.AttrDict

### ISSUE THREAD

**Issue by cacarrara** [elastic/elasticsearch-dsl-py#497]
I was just wondering if wouldn't be good implement the items() method in AttrDict class since its purpose is emulate a dictionary. I was debugging my code and I saw facets attribute are AttrDict objects. As it was a *Dict I tried to call items(), but it wasn't there. 

Also, would be even better implement all expected methods for mapping containers, as described in [Python Docs](https://docs.python.org/3/reference/datamodel.html?emulating-container-types#emulating-container-types)

I don't know it is a real need nor anyone else is already doing it, but I could do that.

**Comment by HonzaKral** [comment]
I understand your reasons but unfortunately I cannot help you. The reason is that people might have a field called `items` on their documents which would then be hidden in a very confusing way and would undermine the meaning of the class.

Also if we implemented one of the methods we would have to implement all for consistency and would take up way too much namespace.

If you wish to work with the raw dictionary feel free to call `to_dict()` and then you will have all the methods available.

Hope this helps.
