### ISSUE TITLE
Documentation for Search.source method is wrong (ES 5.0)

### ISSUE THREAD

**Issue by tylerjharden** [elastic/elasticsearch-dsl-py#503]
According to the documentation, I can limit the fields returned from a Search by calling Search.source, and passing either an array of the field names, or an array kwarg for the "include" keyword.

From my tests, it is not "include", but "includes".

Additionally, if trying the condensed version of just passing a straight away of field name strings, I receive this error:

![image](https://cloud.githubusercontent.com/assets/7143160/20107925/4196d77e-a5a8-11e6-8654-63849d25f022.png)

**Comment by hvdklauw** [comment]
Documentation is wrong for ES5 in a lot of places, and mostly because it doesn't do a lot of checking or mangling of what you pass in, it are just useful object based wrappers.

This particular issue is because the API changed in elastic itself:
[2.X](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-source-filtering.html)
vs.
[5.X](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html)

**Comment by HonzaKral** [comment]
This is solved by https://github.com/elastic/elasticsearch-dsl-py/pull/516

Thank you for the report!
