### ISSUE TITLE
SerializationError: UnicodeDecodeError

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#512]
Hello 

How I can resolve this error:

 UnicodeDecodeError('ascii', '"\xe2\x80\x93q"', 1, 2, 'ordinal not in range(128)'

When I do this:

s = my_doctype_object()

s.full_fill(results)

s.save()

the problemm is that we are saving this information:

u'name': '\xe2\x80\x93q',

**Comment by HonzaKral** [comment]
This is caused by the data - you are using non ascii characters in python 2 `str` type but have the encoding set to `ascii`. The proper fix is to not use `str` but use `unicode` instead.

See https://github.com/elastic/elasticsearch-py/issues/392 and https://github.com/elastic/elasticsearch-py/issues/334 for more details.

Hope this helps.
