### ISSUE TITLE
 Strange behavior: some words breaks search Elasticsearch

### ISSUE THREAD

**Issue by BitcoinKing** [elastic/elasticsearch-dsl-py#524]
I am using http://elasticsearch-dsl.readthedocs.io 0.0.10 and ES 1.7.3

Faced a strange behavior during search: some words that I pass to "should" query  breaks search - search cannot find that words (I see that in console) - but also a lot of other words too.
 In code below  "should" query consist of 1000 clauses.
My guess was that this word is not in vocabulary (I use russian and english morphology config) - but no, with other unseen and special words search is good.
So, when i remove these "problem" words search is working again.
This is super strange - I tested "problem" words with https://django-haystack.readthedocs.io/en/v2.5.0/index.html and ES can find them....

```
    for i in eat_search_raw_list_1024:
        q = Q('bool',
            #must=[Q('match', text='BBQ')],
            should=[(Q("match", text="\'bad service\'~3") | Q("match", text="\'bad eat\'~3")  .........1000 more................],
            minimum_should_match=1, 
            _name=name_query 
        )            
        s = Search(using=client, index="haystack").query(q).query(~Q("match", text=minus_words))    
        s = s.highlight('text', fragment_size=50)  
        response = s.execute()
```

**Comment by HonzaKral** [comment]
Hi, what is it you are exactly trying to do? Can you share an example query that works on console and not via this code?

From looking at this code I think you might want to just pass a list of queries to the should clause, not a single query as you are doing now (combining the individual queries using `|`):
```
            should=[(Q("match", text="\'bad service\'~3"), Q("match", text="\'bad eat\'~3")  .........1000 more................],
````

**Comment by BitcoinKing** [comment]
@HonzaKral  yes, i do search via` | `symbol - it working! But for some words.
Example: i search "KFC" (fastfood company) - i see in console that some posts are found, bot some are not!
I have done `rebuild_index`, also tried to manually insert text to post (to avoid common problem where some characters written in other language than English i.e. "C") - nothing work

**Comment by HonzaKral** [comment]
Looking at your code a second time it looks like you are passing in lucene query syntax into `match` queries which doesn't support those. Haystack uses `query_string` queries which are completely different. If you wish to specify fuzziness for the `match` queries just use the `fuzziness` option - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-fuzziness

I am closing this issue since this is not an issue with `elasticsearch-dsl` but with your queries. The best place to ask questions about different queries would then be https://discuss.elastic.co/

Thank you!
