### ISSUE TITLE
Can't add a _parent field

### ISSUE THREAD

**Issue by matdrapeau** [elastic/elasticsearch-dsl-py#535]
I got this error:
`can't add a _parent field that points to an already existing type, that isn't already a parent`

use this set of classes:

```
class User(DocType):
	username = String()
	website_url = String()

	class Meta:
		doc_type = 'user'
		index = 'my_index'

	def save(self, **kwargs):
		return super(User, self).save(op_type='create', **kwargs)


class Post(DocType):
	content = String()

	class Meta:
		doc_type = 'post'
		index = 'my_index'
		parent = MetaField(type='user')

User.init()
Post.init()
```

Is it the right way to declare a parent-child relationship? I am using ES 2.4

**Comment by brainix** [comment]
Hi, @matdrapeau.

I think that the issue is that you can't use `init()` on your individual models' mappings.  The problem is that when you're using parent/child mappings, the mappings have to be created together.

There might be a couple of different approaches that work, but the way that I do it is to fall back to `elasticsearch-py`'s functionality as necessary.  My order of operations is to:

1.  Create the index using [`es.indices.create()`](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.create).
2.  On the new index, put the analyzers, token filters, and and tokenizers using [`es.indices.put_settings()`](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.IndicesClient.put_settings).
3.  Bulk index all of the `User` and `Post` docs together using [`elasticsearch.helpers.parallel_bulk()`](https://elasticsearch-py.readthedocs.io/en/master/helpers.html#elasticsearch.helpers.parallel_bulk).
4.  Swap the alias from the old index to the new index using [`es.indices.update_aliases()`](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.IndicesClient.update_aliases).
5.  Delete the old index using [`es.indices.delete()`](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.delete).

I hope that this solves your problem, and good luck!

**Comment by matdrapeau** [comment]
@brainix Thanks for the answer!
It seems pretty complex to make relationships working with ES.

For 2: Since I don't have any tokens and analyzers, I could skip that step for now I guess?
For 3: How do you know which action to do and how to execute them?
For 4: Why cannot we just refresh the old index?

Thanks

**Comment by brainix** [comment]
Hi, @matdrapeau.

Indeed.  I adore Elasticsearch, but it isn't a relational database, so relationships can be tricky.  I should've mentioned that my potential solution is for creating a new index.  Once you've created a new index, you can create, update, and delete documents like normal without having to deal with mapping your relationships.  As for as your questions...

For 2:  You're right.  If you don't have any analyzers, token filters, or tokenizers, you can skip this step.

For 3:  You can turn all of your documents into index actions.  For more information on bulk actions, check out [Cheaper in Bulk](https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html).

For 4:  Maybe I was unclear that this solution is for creating a new index.  The reason to use an alias is...  Imagine a production system.  You have a current index serving requests.  In order to do a full reindex of your data, you don't want to bring your site down.  So you create a new index.  While the new index is being built, the old index continues serving requests.  Then only when the new index is ready, you switch the alias, so that the new index serves requests.  Then it's safe to delete your old index.

I hope that this makes more sense!  Good luck!

**Comment by matdrapeau** [comment]
Thanks @brainix 
Sorry to bug again but could you show me exactly how to do #2 in my specific case using an ES-dsl model?

**Comment by fishtreesugar** [comment]
I find we can use [`Index`](http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#index) to create multiple mappings at the same time!

**Comment by HonzaKral** [comment]
Hi, unfortunately this is a limit of elasticsearch itself and not of `elasticsearch-dsl`. The proper solution is, as @fishtreesugar (thanks!) points out, to use the `Index` object.
