### ISSUE TITLE
Cannot add/update Analyzers

### ISSUE THREAD

**Issue by jfinnson** [elastic/elasticsearch-dsl-py#570]
I am unable to add/update analyzers for an Index after it has been created.

The following works if the Index has not been created yet:
`my_index.analyzer(my_analyzer)`

I am able to add/update analyzers via curl but not via the lib.

(Apologies if this is more appropriate for a forum or IRC, but I found none truly helpful or applicable)

**Comment by mattjmcnaughton** [comment]
Would you mind posting the stack trace of the error message that you're getting? Thanks!

**Comment by jfinnson** [comment]
There is no error message or stack trace. Calling`my_index.analyzer(my_analyzer)` simply has no effect? I am currently using es_client.indices.put_settings from elasticsearch-py to get around this issue.

**Comment by HonzaKral** [comment]
The `analyzer` method just defines the analyzer on the `Index` object, it doesn't send it to elasticsearch. Proper way to use this would be to create your `Index` object, set all the settings, including analyzers, mappings (via `doc_type` method) etc and then create the index using the `create` method.

In some cases you can also update the settings using other APIs; but not always, which is why it wasn't a priority to implement (since the support wouldn't be complete anyway).

I am sorry for the inconvenience.

**Comment by jfinnson** [comment]
Thanks for clarifying the analyzer method. 
By "using other APIs" do you mean not via DSL? If so, are you saying that the only time you can specify settings on an index is when you create it?

**Comment by HonzaKral** [comment]
> are you saying that the only time you can specify settings on an index is when you create it?

Typically yes, due to the nature of elasticsearch most settings cannot be updated once index is created. The only way is to close the index, update the settings and then reopen it. To open and close the index you can use the methods on the `Index` class.
