### ISSUE TITLE
Search.filter() does not return a copy of the instance

### ISSUE THREAD

**Issue by kendas** [elastic/elasticsearch-dsl-py#589]
This behavior is inconsistent with most other methods that refine the `Search` instance ([`sort`](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L428), [`index`](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L115), [`source`](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L383), among others).

The same kind of behavior can be observed when using aggregations through the `aggs` member. However, this case is likely more complicated by the following factors:

 * The ability to use the [`__setitem__()`](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/aggs.py#L69) method (from `AggBase`) which does not support the returning of values.
 * When using bucket aggregations, the return type is not `Search`, but a subclass of `Bucket`. ([source](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/aggs.py#L75))

**Comment by HonzaKral** [comment]
Using the `filter` method is just a wrapper around `query` and that actually does clone the `Search` instance and returns a copy (0). If you have a test case where `filter` or `query` doesn't return a copy it's most definitely a bug and really should be fixed.

`aggs` are different, primarily because of the need for chaining - to be able to specify nested buckets and metric aggregations.

Thanks!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L31

**Comment by kendas** [comment]
I looked through my code and discovered that I did not apply the filter I had intended to apply. As a result, the cloning did not take place as I had intended on the filter.

Sorry for the inconvenience.
