### ISSUE TITLE
Aggregation on nested object

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch-dsl-py#610]
Hi there,

I am trying to convert an aggregation on a nested set to the python DSL and I am running in some trouble.
The query looks like this.
```
"features": {
    "nested": { "path": "features" },
    "aggs": {
        "name": {
            "terms": {"field": "features.name.keyword"}
        }
    }
}
```

I have found `.query('nested', path='features', query=Q('match', field='name'))` but by the looks of it it only accepts a Q object and not an A object.

So my question is can this be accomplished with the DSL and if so how.

Thanks in advance!

**Comment by WisdomPill** [comment]
Hi,
The following sould work

    from elasticsearch_dsl import A
    from elasticsearch_dsl.search import Search
    
    name_agg = A('terms', field='features.name.keyword')
    
    s = Search()
    s.aggs.bucket('features', 'nested', path='features').metric('name', name_agg)
    
    print(s.to_dict())

**Comment by WisdomPill** [comment]
Actually this one is better

    from elasticsearch_dsl.aggs import Terms, Nested
    from elasticsearch_dsl.search import Search
    
    s = Search()
    s.aggs.bucket('features', Nested(path='features')).bucket('name', Terms(field='features.name.keyword'))
    
    print(s.to_dict())

**Comment by royfad** [comment]
hi @WisdomPill 

maybe you can help me ? i am having a hard time with the nested aggregation syntax 
i have a documents that store our customer api hits  and i would like to return the data in the level 
account-->user-->end point-->Domain ,sum(hits)
 what should i use ? nested ?

**Comment by WisdomPill** [comment]
Yes, I'd be glad to, I didn't get what you really want to do in your last question.
Can you post your mapping, please? And a comprehensive example of the result you want to obtain?

**Comment by royfad** [comment]
hi 
i have a log that hold json that looks like this :
{
  "_index": "blblb",
  "_type": "logentry",
  "_id": "AV9sl6ObZdPDgfJQR6b2",
  "_score": null,
  "_routing": "10063286",
  "_source": {
    "ip": "00.00.00.00",
    "date": "30-10-2017",
    "time": "09:22:22",
    "url": "blblblbl",
    "apiKey": "229959580ed1bdafc7fbec5caf0d7e41",
    "domain": "499.com.pl",
    "response": 404,
    "endpoint": "blblblb",
    "public": false,
    "hitCost": 1,
    "accountId": 10063286,
    "userId": 892403,
    "timestamp": "2017-10-30T09:22:22.8286229Z",
    "version": "v1",
    "application": "blblblbl"
  },
  "fields": {
    "timestamp": [
      1509355342828
    ]
  },
  "sort": [
    1509355342828
  ]
}

i would like to built an analysis over it using python and then load it into relation DB .
my outcome will be  a table with the granularity 
Account | userid| date| end point|domain|sum(hits)

i was able to get the aggregate to account and i would like to divide it to user and end point and domain.
i am trying to use the elasticsearch_dsl but having some issue with syntax   
can you advise me ?

**Comment by WisdomPill** [comment]
If I got it right, i think what you need is nested term aggregations, not nested aggregations. The latter is to aggregate nested fields, that you're not using by the way.
A query whould be like the following

```json
GET <index>/<type>/_search
{
  "size": 0, 
  "aggs": {
    "accounts": {
      "terms": {
        "field": "account",
        "size": 10
      },
      "aggs": {
        "users": {
          "terms": {
            "field": "user_id",
            "size": 10
          },
          "aggs": {
            "date": {
              "terms": {
                "field": "date",
                "size": 10
              },
              "aggs": {
                "endpoints": {
                  "terms": {
                    "field": "endpoint",
                    "size": 10
                  },
                  "aggs": {
                    "domains": {
                      "terms": {
                        "field": "domain",
                        "size": 10
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
to access the count of the hits there's a field in the result response that has the hits for every bucket.

A query like that can be built in python with the following code.

```python
import json

from elasticsearch_dsl.search import Search

s = Search()
s.aggs.bucket('accounts', 'terms', field='account')\
    .bucket('users', 'terms', field='user')\
    .bucket('dates', 'terms', field='date')\
    .bucket('endpoints', 'terms', field='endpoint')\
    .bucket('domains', 'terms', field='domain')

print(json.dumps(s.to_dict(), indent=4))
```

Hope it helps, and works because I didn't test it and I'm not sure I get your question and why you would do something like this to put it in a relational database since you already have the data in elasticsearch.
But I'm hopeful that you have a reasonable justification.

**Comment by royfad** [comment]
thank you very much ! 
the reason i uploaded the data to DB is because we join it to many other source (sf,piwik,etc)
in our dwh and that is the way we do it 
i have added :
s.aggs.bucket('accounts', 'terms', field='account')\
    .bucket('users', 'terms', field='user')\
    .bucket('dates', 'terms', field='date')\
    .bucket('endpoints', 'terms', field='endpoint')\
    .bucket('domains', 'terms', field='domain')\
    .metric('max_lines', 'sum', field='hitCost')
response = s.execute()

now i just need to figure out how to parse the data from the response 

ps
what is the best way to get all the result and not only 10 ?

**Comment by WisdomPill** [comment]
Well it's like a dictionary for parsing the response.
REMEMBER to set the size to zero, I use [0:0] to make faster queries.
You cannot get all the results.
To get all the results you have to count them first, because this kind of feature was removed in elasticsearch 2.x for memory issues with high cardinality fields.
In my use case I have relational database that stores logs of some sensors in elasticsearch and when I run the aggregations I use include and set all the ids,(which is far more efficient than setting the size), but not in every application is possible. If you don't know the cardinality of your data I suggest you give a try to cardinality aggregation for the count part.

But you can do a pretty inefficient and reasonably bad thing to overcome all of this.
You can set the size of every term to a high number or if you like bad workarounds you could set the size always to the theoretical limit of integer (2147483647).

Last but not least, the doc_count in terms aggregation and the count of cardinality aggregation is aproximate so if you have a small amount of data the returned numbers are probably right.
For more info https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html

Hope it helps.

**Comment by royfad** [comment]
should i add another .metric after each bucket ? 
i remind you that i would like to get the value for each user and the breakdown by  endpoint 
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
client =Elasticsearch([{'use_ssl': False, 'host': 'blblblbl.amazonaws.com', 'port': 80}])
s = Search(using=client)
s = Search(using=client, index="blblbi-2017.10.28").filter("term", response="200")
s.aggs.bucket('per_tag', 'terms', field='userId').metric('max_lines', 'sum', field='hitCost').bucket('per_endpoint', 'terms', field='endpoint').metric('max_lines', 'sum', field='hitCost')
response = s.execute()

ps 
thanks a lot for your help,
where should i add the size=0 ?

**Comment by WisdomPill** [comment]
If I got your request properly you want the sum metric for each term aggregation, the method to achieve this is using sum aggregation after each term aggregation.

To set size 0 use slicing.

Here's an example.

```python
import json

from elasticsearch_dsl.search import Search


s = Search().filter("term", response="200")[0:0]
s.aggs.bucket('accounts', 'terms', field='account') \
    .bucket('users', 'terms', field='user') \
    .bucket('dates', 'terms', field='date') \
    .bucket('endpoints', 'terms', field='endpoint') \
    .bucket('domains', 'terms', field='domain')

s.aggs['accounts'].metric('max_lines', 'sum', field='hitCost')
s.aggs['accounts']['users'].metric('max_lines', 'sum', field='hitCost')
s.aggs['accounts']['users']['dates'].metric('max_lines', 'sum', field='hitCost')
s.aggs['accounts']['users']['dates']['endpoints'].metric('max_lines', 'sum', field='hitCost')
s.aggs['accounts']['users']['dates']['endpoints']['domains'].metric('max_lines', 'sum', field='hitCost')

print(json.dumps(s.to_dict(), indent=4))
```

I know it's kind of ugly to assign it like this, I think you can probably create a recursive function that adds the metric for each bucket.

Hope it helps.

**Comment by royfad** [comment]
HI 
for feature developer i think i figure out this code 
can you please take a look and tell me if it looks ok for your opinion ?
this code works and give me the correct results  (i will write the date filter dynamically )


        with open(kwargs['file_path'], 'wb') as csv_output_:

            writer_ = csv.writer(csv_output_,
                                 delimiter=str(kwargs.get('csv_delimiter',
                                                          DEFAULT_DELIMITER)),
                                 quotechar=str(kwargs.get('csv_quotechar',
                                                          DEFAULT_QUOTE)),
                                 quoting=csv_quoting_mode)

            client = Elasticsearch([{'use_ssl': False,
                                     'host': 'blblblblb.us-east-1.es.amazonaws.com',
                                     'port': 80}])
            s = Search(using=client).filter("term",response="200").filter("term",date="04-11-2017")
            count = s.count()
            s.aggs.bucket('per_account', 'terms', field='accountId',size=count).bucket('per_user', 'terms', field='userId', size=count).bucket(
                'per_endpoint', 'terms', field='endpoint' ,size=count).bucket(
                'per_domain', 'terms', field='domain',size=count).metric('max_lines', 'sum', field='hitCost')
            print 'start'
            response = s.execute()
            for account in response.aggregations.per_account.buckets:
                for user in account.per_user.buckets:
                    for endpoint in user.per_endpoint.buckets:
                        for domain in endpoint.per_domain.buckets:
                            row=(account.key, user.key, endpoint.key, domain.key.encode('utf-8'), domain.max_lines.value)
                            writer_.writerow(row)

**Comment by HonzaKral** [comment]
Hi @royfad, yes, that looks good, definitely. Only tiny thing I would say is to not instantiate `Elasticsearch` inside your method but instead have a global one to be reused to make use of the persistent connections.

Thank you, @WisdomPill, for help!
