### ISSUE TITLE
Delete by field

### ISSUE THREAD

**Issue by aayushiku** [elastic/elasticsearch-dsl-py#621]
I have an index with multiple documents. Eg

[
{
   "id" : 4,
   "object" : 3,
},
{
   "id" : 3,
   "object" : 5,
},
{
   "id" : 5,
   "object" : 3,
}]

Now I want to delete just the ones with object = 3 in one query/bulk operation. Somebody please help. i have been looking for hours but to no avail.

**Comment by HonzaKral** [comment]
Hi @aayushiku, you can use the new `delete` method on `Search` object that will trigget a `delete-by-query` (0) operation:
```
s = Search()
s = s.filter('term', object=3)
s.delete()
```

Unfortunately this hasn't been released yet so you'd have to use the git version. Alternatively just have a look at the method's implementation (1) so that you can do the same in your code.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html
1 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L648

**Comment by aayushiku** [comment]
@HonzaKral Thanks for the help. :) Can you let me know when you are planning to release this feature. Will take the call accordingly. Thanks.

**Comment by HonzaKral** [comment]
Sorry for the delay, it has just been released as `5.2.0`
