### ISSUE TITLE
How can I search more them one field using query_string ?

### ISSUE THREAD

**Issue by fellipeh** [elastic/elasticsearch-dsl-py#630]
I`m using these:

```
search.query("query_string", query=self.query_string)
```

I have a dynamic model.

How can I make a query_string, to search with more them one field?

Regards

**Comment by HonzaKral** [comment]
Hi, by default `query_string` will search the `_all` field, if you want to run on multiple fields just use the `fields` parameter as per [0]: `s.query('query_string', query=self.query, fields=['f1', 'f2'])`

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_multi_field

**Comment by fellipeh** [comment]
Ok,

So, I need to do something like that:

Field1="Test"  AND  Field2="OtherTest"

or do that:

Field1="Test"  OR  Field2="Test"

Can I do that, using query_string?

**Comment by HonzaKral** [comment]
You can do that by using `query_string` (`s.query('query_string', query="field1:test OR field2:otherTest")`) but I wouldn't recommend it since it requires you to glue together strings and is very brittle (a syntax error would result in an exception). I would suggest instead using the dsl itself to compose the query in python using atomic queries like `match` [0]: `s.query(Q('match', field1='test') | Q('match', field2='otherTest'))`

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html
