### ISSUE TITLE
Facets with sub-aggregation

### ISSUE THREAD

**Issue by fellipeh** [elastic/elasticsearch-dsl-py#639]
How can I make facets using sub-aggregation?

I have these code:

```
facets = {
        'latlong': TermsFacet(field='latlong'),
        'datasets': TermsFacet(field='dataset'),
        'datatype': TermsFacet(field='datatype'),
    }
```

I need to do like these:

facets = {
        'latlong': TermsFacet(fields='latlong, dataset'),
    }

But doesn't work..

How can I do that?

Regards

**Comment by HonzaKral** [comment]
Unfortunately we do not currently support nesting `Facet`s in `FacetedSearch` and there is no plan to add those due to the complexity involved. The workaround is to create a custom `Facet` subclass for your particular use case that would handle the nesting by producing the appropriate aggregations and filters.
