### ISSUE TITLE
Please correct the default value of minimum_should_match in query-dsl part

### ISSUE THREAD

**Issue by anhzhi** [elastic/elasticsearch-dsl-py#663]
https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/query.py#L112
https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/query.py#L151

0 is supported, percentage string like "100%" is supported
while 
1 not supported, 
float or float percentage string  like "100.2%"  are not supported
I am not sure whether this issue belongs to es or es-dsl-python

**Comment by HonzaKral** [comment]
I am afraid I don't understand - 1 as value for `minimum_should_match` is indeed supported as mention in the documentation (0) as indeed the default for a query with just `should` clauses or if used in filter context (1).

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html
1 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

**Comment by anhzhi** [comment]
ES version: 5.3.1
Test Case :
```
POST /cc-packetbeat-test-*/_search
{
   "query": {
      "bool": {
         "minimum_should_match": 1,
         "filter":             {
           "query_string": {
              "query": "http",
              "analyze_wildcard": true
           }
        }
      }
   },
   "from": 0,
   "size":1
}
```
Response as follow:
```
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 2,
      "successful": 2,
      "failed": 0
   },
   "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
   }
}
```
If the value of minimum_should_match set to 0, i will get the response like:
```
{
   "took": 3261,
   "timed_out": false,
   "_shards": {
      "total": 2,
      "successful": 2,
      "failed": 0
   },
   "hits": {
      "total": 168702874,
      "max_score": 0,
      "hits": [
            ……
            ……
       ]
    }
}  
```

**Comment by HonzaKral** [comment]
Minimum should match relates to the `should` clause. In your test case you have 0 queries in the should clause yet you say that at least one must match. Such query will never match but it doesn't mean that 1 is not a supported value.

`minimum_should_match` simply specifies how many (or what percentage) of otherwise optional queries in `should` clase of the `bool` query are required.

**Comment by anhzhi** [comment]
May the clue i gave is wrong, that mislead you.
please help me to check the code as below:
```
from elasticsearch_dsl import *
import json
search = Search()
q = Q('bool') | Q('match', appname=dict(query="packetbeat", type="phrase"))
search = search.query(q)
q = Q('range', **{'@timestamp': {'to': 1494930146976, 'from': 1494926546976}})
search = search.query(q)
print json.dumps(search.to_dict())

f = Q('query_string', query="http", analyze_wildcard=True)
search = search.filter(f)
print json.dumps(search.to_dict())
```

the output is correct, and the query get hits as expected:
```
{"query": {"bool": {"minimum_should_match": 1, "should": [{"match": {"appname": {"query": "packetbeat", "type": "phrase"}}}], "must": [{"range": {"@timestamp": {"to": 1494930146976, "from": 1494926546976}}}]}}}
```
the second is difficult to understand, and the query will get no hits
```
{"query": {"bool": {"minimum_should_match": 1, "filter": [{"query_string": {"query": "http", "analyze_wildcard": true}}], "must": [{"range": {"@timestamp": {"to": 1494930146976, "from": 1494926546976}}}, {"match": {"appname": {"query": "packetbeat", "type": "phrase"}}}]}}}
```

**Comment by HonzaKral** [comment]
Ah, thank you for this example. I think I finally understand the issue here - the `minimum_should_match` here in your example is thrown off by the empty `bool` query where I don't check for existence of `should` and assume it exists when specifying default value of `minimum)should_match` at [0].

For now the workaround for you is to just say:
`q = Q('match', appname=dict(query="packetbeat", type="phrase"))`
which should work.

Thanks again for the report and patience with me :)

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/query.py#L112

**Comment by anhzhi** [comment]
yes, that's it.
my suggestion in the title is not the root cause.

**Comment by HonzaKral** [comment]
Thanks again for the patience and the report!
