### ISSUE TITLE
Change Meta attribute interactively

### ISSUE THREAD

**Issue by sabban** [elastic/elasticsearch-dsl-py#689]
Hi,

I have this declaration:
from elasticsearch_dsl import DocType

```python
class Event(DocType):
   some_field = String()

    class Meta:
        doc_type = 'events'   
```

I would like to change interactively the doc_type value just before use the save method of my Event class. Is there a way to do this properly ?

Thank you very much for your work and help.

Regards,
Manuel Sabban

**Comment by HonzaKral** [comment]
Hi @sabban,
can I ask what is your use case for changing the `doc_type` on a per-document basis? When I designed the `DocType` class I was thinking of it representing a single doc type in an index - I would love to know where this thinking came short of helping you with your problem before I decide on any API changes.

Thanks!

**Comment by sabban** [comment]
Hi @HonzaKral,

Yes, that make sense. 

We want to store logs in a DocType defined way in elasticsearch. Until recently we used only the bulk helper to do that, and it allowed to choose the doctype name at runtime (in fact in a configuration file). But now, I added DocType.save fallback in case the bulk helper fails, and this make me hardcode the doctype name. I had this sentiment that this is a regression on our side... But I may not be doing things the right way.

Thanks !

**Comment by HonzaKral** [comment]
Really if you have multiple types you should use multiple `DocType` subclasses. If the types are not different enough to warrant their separate `DocType` subclass I don't believe they should be separate types in elasticsearch either. That is my thinking when it comes to document types.

This, along with the fact that types are slowly going away (0) leads me to close this issue. As a workaround I would suggest adding custom `to_dict` method that will (if `include_meta` is `True`) change the `_type` in the output manually based on some logic/attribute.

Hope this helps

0 - https://www.elastic.co/blog/index-type-parent-child-join-now-future-in-elasticsearch

**Comment by brizzbane** [comment]
I think this might be the right place to ask..  It is the 4th result in google for

> elasticsearch_dsl change meta index value

I'm wanting to do this before save: 

`b_record.Meta.index = '%s-%s' % b_record.Meta.index, datetime.strftime(datetime.today(), '%d-%m-%y')`

My current value of index is:
```
    class Meta:
        index = 'pmta-b'
        doc_type = 'record_b'
```

Right now, I have all my elasticsearch_dsl 'docs', in a docs.py file.  I import into my main file, records-b.py.  This is a program that reads from stdin, piped from PowerMTA config (mailing program).

The issue I am having is that the date of the index will be whatever the day was when PowerMTA was last started or config reloaded.  So I think the values are being cached (maybe because I'm importing from docs.py?).

So I tried adding in:

`b_record.Meta.index = '%s-%s' % b_record.Meta.index, datetime.strftime(datetime.today(), '%d-%m-%y')`

right before save, but my index value stays as the original b_record.Meta.index value.
`'pmta-b'.`

Can you help?  Thanks!
