### ISSUE TITLE
Elasticsearch indices param in snapshotting

### ISSUE THREAD

**Issue by aayushiku** [elastic/elasticsearch-dsl-py#715]
Elasticsearch has the provision of providing the indices to be backed up. Can we have that param in this library as well?

**Comment by HonzaKral** [comment]
This library currently doesn't support the `snapshot` functionality since there isn't much need for abstraction. To issue a `snapshot` API call please use the underlying `elasticsearch-py` client (0).

0 - https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.SnapshotClient.create
