### ISSUE TITLE
Let Index.doc_type override DocType index multiple times

### ISSUE THREAD

**Issue by gilbsgilbs** [elastic/elasticsearch-dsl-py#746]
Hi,

[This line](https://github.com/elastic/elasticsearch-dsl-py/blob/fb830eb/elasticsearch_dsl/index.py#L78) prevents the `doc_type` function from overriding the `DocType` default index more than once. However, I have to handle multiple configurations with nested contexts.

I don't see any good reason for this function to perform the check. Maybe it's because of dynamic mapping? It's kind of unexpected to me (and looks buggy). If I call `doc_type` function multiple times, I would expect the `doc_type` to be mapped to what was specified by the latest call. I would suggest to remove this condition, or at least add a `allow_override` flag which would default to `False` (to avoid breaking changes). What do you think?

Thanks.

**Comment by HonzaKral** [comment]
Hi @gilbsgilbs, thanks for raising this issue!

My initial motivation for this was to to make assigning a doc type to an index as easy as possible. I assumed that, if anybody needed a doc_type to be assigned to multiple indices, they would handle that explicitly by defining the `index` themselves.

I see several different solutions when calling `Index.doc_type()` multiple times, with various tradeoffs:

1.  don't touch the `DocType`'s index metadata - use it purely to register the doc type to the index
2. always override `index`
3. override only if there is no default (current behavior)
4. allow `index` to be a list so multiple calls will just add the name to it

I am leaning towards `4` which only has the downside of rendering the `index=` parameter to `save()` required for new docs since otherwise we won't be able to determine where we should save the new document.

**Comment by gilbsgilbs** [comment]
> My initial motivation for this was to to make assigning a doc type to an index as easy as possible. I assumed that, if anybody needed a doc_type to be assigned to multiple indices, they would handle that explicitly by defining the index themselves.

I reckon the underlying problem is that the index configuration is global and static (unless you explicitly pass an index for each request). It would be handy if there were some kind of "in-between" solution, such as client instance or context manager in which we could define custom mappings and configuration in a flexible way (among other stuff). Definitely looks less global and more elegant to me. The lack of flexibility in configuration is the highest source frustration I had using `elasticsearch-dsl-py` so far (have a couple more examples that I find legitimate but are just either counter-intuitive or a real pain to use). (And don't get me wrong, I really do think this project is really great and useful otherwise).

A proper workaround for my issue is to pass the index explicitly for each call I make to ES, that's true. Yet, it quickly gets clumsy, and separating configuration from code was one of the original reason I didn't want to use vanilla `elasticsearch-py` in the first place. I'll stick to my dirty workaround that is patching `_doc_type.index` manually for now. I should have enough tests to raise an alert if anything breaks in further releases.

> I see several different solutions when calling Index.doc_type() multiple times, with various tradeoffs:
> […]
> I am leaning towards `4`

Mmh, maybe there's no "expected" solution after all 🤔 . I'd really not have expected `4`. In this case, why not just `logger.warning`, just to state explicitly that you shouldn't be doing this? And defer new use-cases to later.

Thanks a lot for your explanations :) . Feel free to close this issue if you think there's nothing to do.

**Comment by HonzaKral** [comment]
Thanks for the feedback, for now let's leave it as it is and we will see how people use this library once 6.x is out, which will have no types.
