### ISSUE TITLE
how to store fields with empty values?

### ISSUE THREAD

**Issue by yyz1989** [elastic/elasticsearch-dsl-py#758]
Hi all,

When I store documents containing empty values, those empty fields are automatically discarded and not stored by elasticsearch. According to https://www.elastic.co/guide/en/elasticsearch/reference/current/null-value.html, we should be able to index and search field of null values or empty lists when providing a "null_value" parameter to the field definition. How should we define it here? I tried to put it into Meta property and also initializer of DocType classes, but it did not work.

Any hint is highly appreciated. Thank you very much and have a nice day!

Best regards,
Yang

**Comment by HonzaKral** [comment]
Hi @yyz1989, unfortunately the library doesn't actually serialize empty values (`None` and `[]`) as they typically bring nothing to the table and just take up space. What I recommend instead is to either accept this and use NOT `exists` query to looks for documents that don't have this field or, at python level, assign a "sentinel" value to the field instead of leaving it empty.

Hope this helps,
Honza

**Comment by HonzaKral** [comment]
also see https://github.com/elastic/elasticsearch-dsl-py/issues/460 for more details on the background

**Comment by yyz1989** [comment]
Hi @HonzaKral, I see, thanks a lot for the explanation!
