### ISSUE TITLE
Allow multiple doc_types

### ISSUE THREAD

**Issue by ChaosMTA** [elastic/elasticsearch-dsl-py#761]
Hey guys,

I was wondering if there would be a way to allow me to set the doc_type in the meta of my DocType class to be a list for two different types?

Otherwise, and sorry to ask this here. Is there a way to change all entries in a index to be the same type? Seems when I moved to a new server they started being set as '_type': 'doc' however the previous entries are set as '_type': 'log'...

Thanks

**Comment by WisdomPill** [comment]
Short answer no, you cannot change the type of a document after it is indexed.
Long answer there are several workarounds, you can for istance reindex an index and change the type with a script or using a script processor inside an ingest pipeline that you put in the reindex call.
In the first case I wrote a little example that could help you.

In this example I have documents representing a blog post, but for some reason I may have the same structure but the name of the type is article instead of post. I wrote the following reindex api call to change the type of all the articles to be post.

``` json
POST _reindex
{
  "source": {
    "index": "blog"
  },
  "dest":{
    "index": "new_blog"
  },
  "script":{
    "lang": "painless",
    "source": "if(ctx._type == 'article'){ctx._type = 'post'}"
  }
}
```

Hope it helps.

**Comment by ChaosMTA** [comment]
Thanks @WisdomPill ES is removing these _types in version 6 anyways aren't they? So wouldn't it be a good idea for this repository to not filter out by _type or at least allow a list of multiple types?

A question about your example, would it be possible to keep the same index name? Thanks for the small script though I'll have to run it on my servers.

**Comment by WisdomPill** [comment]
No, you cannot change the type after a document has been indexed, but you could copy them with a different type even preserving the _id. After that you could delete the old documents. If I may suggest to you a better solution (in my opinion), I would reindex the documents in another index for performance and simplicity reasons. And use an alias to switch the pointed index. Furthermore it's easy to go back if you make mistakes in your script.

If you do it in-place (same index) you will use more storage since the documents deleted are not really deleted until you force merge the segments, (procedure that is not advised if you keep updating the destination index).

Hope it helps.

**Comment by ChaosMTA** [comment]
That just seems weird since filebeat stopped supporting you changing the doc_types unless you really need to. And ES is removing the whole _type specification all together.

https://discuss.elastic.co/t/specifying--type-with-filebeat/94957/4

So what's the point in this API not allowing me to search all doc_types at once? I can't seem to find a way to allow it to search through all types while using a model class.
