### ISSUE TITLE
Boolean field serialization

### ISSUE THREAD

**Issue by wowkin2** [elastic/elasticsearch-dsl-py#788]
Deserialization for Boolean field is not working correctly. It uses `bool()` function that gives following:
``` python
In[1]: bool('0')
Out[2]: True
bool('1')
Out[3]: True
bool('False')
Out[4]: True
bool('false')
Out[5]: True
bool('')
Out[6]: False
```
Should be replaced with something like:
```python
bool(data.lower() in ['y', 'yes', '1', 'true'])
```

**Comment by HonzaKral** [comment]
Actually values like `"y"` or `"yes"` and not valid boolean types for elasticsearch (see 0). I also see no reason to support string `"false"` but I can see how we should support that as well since elasticsearch supports it.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/6.0/boolean.html
