### ISSUE TITLE
Slicing twice doesn't work

### ISSUE THREAD

**Issue by konstin** [elastic/elasticsearch-dsl-py#799]
Iterators are expected to allow slicing twice, i.e.

```python
>>> list(range(0,100)[10:15])
[10, 11, 12, 13, 14]
>>> list(range(0,100)[10:][:5])
[10, 11, 12, 13, 14]
```

This means essentially that `[a:a+b]` equals `[a:][:b]`

With a `Search` object slicing twice doesn't work:
 
```python
>>> Search()[10:15].to_dict()
{'from': 10, 'query': {'match_all': {}}, 'size': 5}
>>> Search()[10:][:5].to_dict()
{'from': 0, 'query': {'match_all': {}}, 'size': 5}
```

(Sorry for submitting an incomplete issue first, I accidentally hit the wrong key)

**Comment by lolletsoc** [comment]
Hey @konstin,

I've created a [branch](https://github.com/lolletsoc/elasticsearch-dsl-py/commit/a4454a41b505932539dee6175b4b260cb2406355) in my fork with minor changes to support this. Take a look at the tests and let me know - specifically [this](https://github.com/lolletsoc/elasticsearch-dsl-py/commit/a4454a41b505932539dee6175b4b260cb2406355#diff-827c411d2c2c7245409bfd8eaa3b197fR250) one.

@HonzaKral, what do you think?

**Comment by konstin** [comment]
Hi @lolletsoc, the changes does solve the issue with slicing twice.

The behavior for slicing multiple times still doesn't match the expected pythonic behavior though. Even though I doubt anyone uses this in realit

```python
>>> list(range(0, 100)[10:][:5][5:])
[]
>>> Search()[10:][:5][5:].to_dict()
{'query': {'match_all': {}}, 'from': 15, 'size': 10}
```

**Comment by lolletsoc** [comment]
Yeah, exactly why I pointed you at that test. If we try to mold this around the pythonic way, we're going to end up with ```{'query': {'match_all': {}}, 'from': 0, 'size': 0}```. Will wait on @HonzaKral's reponse - maybe he has some insights.

**Comment by HonzaKral** [comment]
Thanks for raising this issue @konstin, I understand the confusion. Right now any slicing will reset the `from`/`size` combination which may be unexpected. What people might be looking for is additive slicing - further limiting the scope, what python's lists do and even what django's querysets do (0).

That sounds very reasonable to me and I think we should do it, we just need to be careful about documenting it properly since it is a breaking change.

Thanks again for bringing it up!

0 - https://github.com/django/django/blob/master/django/db/models/sql/query.py#L1603-L1624
