### ISSUE TITLE
Anyway to set up Persistence so that .get() and .save() work on different indexes?

### ISSUE THREAD

**Issue by brizzbane** [elastic/elasticsearch-dsl-py#80]
Problem is that I would like to create daily indices, like "index-02-22-15", but be able to 'get' an index document by id--that would search "index-*"

**Comment by HonzaKral** [comment]
Unfortunately elasticsearch doesn't allow use of wildcards with the `get` api. That means that we always have to explicitly supply the index. Currently you can do it manually on a per-document basis - set the `DocType`'s `index` to `'index-*'` (so that `.search` will work as expected) and make sure that every time you call `.save` or `.get` you explicitly pass in the the value of index:

    d = MyDoc.get(id=42, index='index-2015-01')

You can even override `.save` to extract the index name from the document itself:

    def save(self, *args, **kwargs):
        kwargs['index'] = kwargs.pop('index', 'index-%s' % self.timestamp.strftime('...'))
        return super().save(*args, **kwargs)

In the future I hope to have `TimeBasedIndex` class that will be able to do most of this automatically, but its API is hard to peg down.

**Comment by brizzbane** [comment]
OK, cool, thanks for the reply.  So for get, you'd basically have to do a search first to get the index that it is in, correct?

**Comment by HonzaKral** [comment]
Yes, at which point the `get` becomes unnecessary since you will already have the document.

**Comment by HonzaKral** [comment]
Considering this solved since there is nothing we can do otherwise.
