### ISSUE TITLE
Persistence mutates its arguments

### ISSUE THREAD

**Issue by dpatterson-aio** [elastic/elasticsearch-dsl-py#815]
When you call `SomeDocType(**kwargs).save()` then it can mutate the `kwargs`. I think that's an undesirable side-effect. The smallest example where I can reproduce this involves nested list+object types. Here it is:

```python
from elasticsearch_dsl import DocType, Object, Text

class Thing(DocType):
    nested = Object(multi=True, properties={
        'first': Object(properties={'second':Text()})
    })
    class Meta:
        index = 'thing'

Thing.init()
nested = [{'first': {'second': 'hello world'}}]
Thing(nested=nested).save()

print(type(nested))     # <class 'list'>, as expected
print(type(nested[0]))  # <class 'elasticsearch_dsl.field.InnerObjectWrapper'> !!
```

Does that seem like a problem? As a result, I currently have to deepcopy a bunch of things before saving them.

**Comment by HonzaKral** [comment]
I think this is not an issue on `6.0` as we changed how (de)serialization works and we require users to pass in the appropriate python objects instead of `dict`s etc. - then we don't have to do any in place modifications.

Also the way I think about it, when passing in data via `**kwargs` is that it is the equivalent to setting all the attribues on the object itself (`Dco(**{"k": v})` being the same as `doc = Doc(); doc.k = v`). At that point you are allowing `doc` to take ownership of `v`, including the permission to mutate it if needed for proper serialization according to the rules defined on the `DocType` class and its `Field`s.

Hope this helps!

**Comment by dpatterson-aio** [comment]
cool, thanks for the quick response. I tried that example using elasticsearch-dsl==6.1.0/elasticsearch==6.1.1 and got the same mutation (`InnerDoc` instead of `InnerObjectWrapper`) but anyhow, if that's expected, then no worries. it's not the worst thing to work around.

**Comment by XiaohuanIT** [comment]
ImportError: cannot import name InnerObjectWrapper. And I use the library is elasticsearch==6.2.0, elasticsearch-dsl==6.1.0。`from elasticsearch_dsl import InnerObjectWrapper`

**Comment by anhzhi** [comment]
i think its a BIG problem， which can easily lead to bug and confusion.
first,   input object mutated in constructed function,    developers puzzled a lot.
second,    detailed leads to change, while lazy leads to no mistake.
```
from elasticsearch_dsl import DocType, Object, Text
# lazy codes 
class Thing(DocType):
      pass

nested = [{'first': {'second': 'hello world'}}]
Thing(nested=nested)

print(type(nested[0]))  # dict !!! no mistake
```
