### ISSUE TITLE
FacetedSearch's facets property has limited amount of buckets

### ISSUE THREAD

**Issue by atlasstrategic** [elastic/elasticsearch-dsl-py#823]
I've been using the FacetedSearch functionality successfully. All seems to be working well. The `facets` property is added to the response returned from the FacetedSearch object. I am able to access a dictionary with lists of buckets (each with appropriate tuple of key, document count and flag).

The problem is that there seems to be a hard limit on the amount of "buckets" (exactly 10 or less). I'm not referring to the results per facet—just the total amount of buckets.

**Example**
Lets assume a search query generates 300 total hits spread over 13 categories for a particular query. 
```python
response = blog_search.execute()

total_hit_count = response.hits.total  # 300
accumulated_facets_hit_count = 0
category_count = 0

for category, hit_count, is_selected in response.facets.category:
    accumulated_facets_hit_count += hit_count
    category_count += 1
```
When checking the results we have the following unexpected results:
```python
 # This will give `category_count 10` instead of expected `category_count 13`
print('category_count: ', category_count)

# This will give `False` instead of expected `True` 
print(accumulated_facets_hit_count == total_hit_count)
```
Is there a way to increase the limit of amount of buckets?

**Comment by WisdomPill** [comment]
I think the problem is that you have to specify a size for the term aggregation, as it is by default 10.
Now I don't know if it is a bug but at first glance it seems to me that you cannot specify the size in the TermsFacet. Maybe we need to extend the TermsFacet to include aggregations options, but it depends on how it will be used and why someone would need it as usually elastic search is used as a relational database where it is not. So my question is why do you need it? And last but not least, are you sure you need it?

**Comment by atlasstrategic** [comment]
@WisdomPill thank you for your comments. Yeap, according to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html) there exists such a `size` option. 

> to define how many term buckets should be returned out of the overall terms list

For my use-case, all search results are grouped within the resulting buckets (showing the top 5 results per bucket). Currently, if the search query produces greater than 10 buckets, some buckets are left out and the user can not see the results related to those buckets. For example, imagine a search produces results within 20 countries. Where a bucket represents a country, the user will only see 10 counties to facet on instead of 20.

Maybe It would be useful to be able to increase the size parameter for TermsFacet?

**Comment by WisdomPill** [comment]
Digging into the library code I discovered that you can pass extra parameters as well to the TermsFacet like the size on the initialization of the Facets. You can find it in faceted_search.py in line 22 and used in line 28 when creating the aggregation object. However if you want to specify an optional parameter every time you execute a FacetedSearch then we need to modify the behavior of the Facet object in order to give the developers more flexibility. In conclusion I want to express my hesitancy on the subject as the terms aggregation is not built for this purpose. As I said in the previous comment, elastic search is not a relational database and using it in that manner could produce problems with memory management on you cluster. Although the developer freedom should be considered also helping new developers not to use some kind of habits is very important. In conclusion I would ask @HonzaKral about this subject.

**Comment by WisdomPill** [comment]
Ops... I forgot an example on how to set the size parameter on any other parameter as well

```python
from elasticsearch_dsl import TermsFacet

tf = TermsFacet(fields='text', size=10)
print(tf.get_aggregation())
```

Hope this helps.

**Comment by atlasstrategic** [comment]
Thank you @WisdomPill — works like a charm. I simply added it to my `FacetedSearch` class within the facets declaration like so:
```python
facets = {
        'type': TermsFacet(field='result_type'),
        'country': TermsFacet(field='country_code', size=15),  # 10 -> 15
    }
```
