### ISSUE TITLE
Example Help: Multiple Fields to Create "set()" with Aggs

### ISSUE THREAD

**Issue by dwissm1** [elastic/elasticsearch-dsl-py#826]
I am trying to figure out how I can add multiple fields into a aggregation.  
In my case, I want to create a UNIQUE list of network 4-tuple (source_ip, source_port, dest_ip,dest_port) and return that.

I have done it with an individual field by creating a bucket and it works perfectly.  I know i can create a viz in Kibana to show the resuts I want with a count and I can see the json that Kibana sends but I am not sure how to do it in DSL.

In #136 you provided a link to example..(thank you!) but I didnt seem to find anything that fit.
 
I tried 
.bucket("srcip", "terms", field="srcip")
.bucket("srcport", "terms", field="srcport")
.bucket("dstip", "terms", field="dstip")
.bucket("dstport", "terms", field="dstport")

Is that correct?  It runs, but doesnt mean the output is the intended result.

Thanks in advance.

**Comment by WisdomPill** [comment]
It is right but, you should not use it if you want all the tuples because of the size of the bucket aggregation which by default is 10. You can tweak the size parameter for your needs but beware that high values can consume a lot of ram for caching purposes. And a possible optimization on the top of my head. You are using a nested aggregation that is really heavy for your cluster, I'm assuming from the naming of your fields that you have lots of data. So I would suggest to create a keyword field with all the fields concatenated. In conclusion aggregating for only for that field could give you better performance and a simplify your query.

Hope it helps!

**Comment by HonzaKral** [comment]
the specified aggregations will group documents based on those for values - for any unique combination you will get a group. Note, however, that by default only `doc_count` will be returned for each group and only top 5 values will be returned for each level (top 5 `srcip`s, top 5 `srcport`s for those ips etc...)

I would second @WisdomPill's suggestion to denormalize those values into a `connection` field which you can then aggregate on much more easily. You can also do this at run time using a `script` instead of `field` that will produce the concatenated representation of the 4 falies.

Hope this helps!

**Comment by dwissm1** [comment]
Excellent feedback, thank you @HonzaKral and @WisdomPill.  That is really helpful.

One additional question in reference to this comment @WisdomPill :
"It is right but, you should not use it if you want all the tuples because of the size of the bucket aggregation which by default is 10. You can tweak the size parameter for your needs but beware that high values can consume a lot of ram for caching purposes."
-- I passed size=s.count() where s.count() = the Search results that the aggregation is run over.  Even after I defined that value I still only got 10 results.  Is there an additional parameter that I am missing?

thanks again for your help.
