### ISSUE TITLE
Calling Update on Documents containing Painless scripts saves the script as an attribute to the document

### ISSUE THREAD

**Issue by kurtiskurtis** [elastic/elasticsearch-dsl-py#848]
Calling Update on Documents containing Painless scripts saves the script as an attribute to the document instead of evaluating the script.

**Comment by kurtiskurtis** [comment]
`document = {
   'seen_count':1,
   'field_2':'value_2',
   ....
   ..
   .
   'script':{  
      'script':{  
         'lang':'painless',
         'inline':'ctx._source.seen_count += 1'
      }
   },
   ....
   ...
   ..
   .
}
doc.update(document)
`

results in a document that has an attribute "script" rather than the evaluation of the script (increase seen_count by 1)

**Comment by WisdomPill** [comment]
Hi, the library is not designed for this kind of work. Actually scripts in elasticsearch are designed to add logic to your queries because you don't have a programming language do so for addition subtraction and so on. What you're trying to achieve can be done from python itself. It doesn't work because when the library tries to serialize your object it casts it to a string. We could add scripts but i don't see the point in doing that.

Hope it helps. WisdomPill

**Comment by HonzaKral** [comment]
we need an explicit support of scripted updates, closing this in favor of https://github.com/elastic/elasticsearch-dsl-py/issues/787

Thank you!
