### ISSUE TITLE
Nested Search

### ISSUE THREAD

**Issue by Ameya-Pandya** [elastic/elasticsearch-dsl-py#854]
Hi,
I have my mapping like this:

`{
   _type="user_data",
_source={
    "username": "abc",
    "data":{
        "display_name": "pqr"
    }
}
}`

I want to filter my search in elasticsearch using the `display_name`  how can I do so??

I am new elasticsearch and based on the answers I found on stackoverflow,  I have tried this:

`
display_name_search = display_name_search.query(
        "nested", path="user_data", query=Q("data", display_name="pqr"))
`

Have I done something wrong? Please Help..

**Comment by HonzaKral** [comment]
In this case `data` doesn't have to be defined as `nested` (which is a special field in elasticsearch) and you can just refer to the field using dot notation: `data.display_name`.

If the field is indeed specified as nested then you just need to modify it to include the path in the inner query:
```python
display_name_search = display_name_search.query( "nested", path="data", query=Q("match", data__display_name="pqr"))
```

note that we are using `__` instead of `.` to allow the field to be a keyword argument, that is a syntactic sugar provided by this library.

Hope this helps!
