### ISSUE TITLE
Setting refresh-parameter when updating document

### ISSUE THREAD

**Issue by OskarPersson** [elastic/elasticsearch-dsl-py#855]
How do I set the [`refresh`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html)-parameter when updating a document?

When creating or deleting a document I can use `save(refresh=True)` or `delete(refresh=True)` but when running `update(refresh=True)` a `refresh`-field is added to the document instead of refreshing.

**Comment by WisdomPill** [comment]
Hello I think you're confusing the refresh action with the parameters passed in the query.
You're seeing this kind of behavior because the classic **kwargs argument is used in different manners. As in delete and update (line 279 and 393 of document.py) **kwargs is merged to document meta on the query parameters (of the request like POST or GET) that are sent to elasticsearch. Meanwhile the **kwargs argument is used for the fields to add or update in the update method (line 336 of document.py). You're confusing the parameter that elasticsearch doesn't get in the save and delete method with the refresh action that is a simple post on /<index_name>/_refresh to make your changes available for search immediately.

Hope it helps, WisdomPill

**Comment by HonzaKral** [comment]
Thank you for the explanation, @WisdomPill !

I added a support for `refresh` when calling update for consistency, hope this helps, @OskarPersson
