### ISSUE TITLE
Enforce Mappings while instantiating DocType using Python dict

### ISSUE THREAD

**Issue by rohansb** [elastic/elasticsearch-dsl-py#858]
@HonzaKral referring to your answer here: https://stackoverflow.com/a/45313746/6341371

`MyDoc(**my_dict)` where MyDoc extends DocType

It seems that indexing documents in this way would ignore the Mappings defined in MyDoc. How do we enforce mappings.

Further, Are there any tricks to filter the JSON as well based on the defined mappings?

**Comment by HonzaKral** [comment]
To define the mappings just use the `Index` object (0) or use the `init` classmethod on `MyDoc` which will create the mappings in elasticsearch.

There is currently no tools or tricks to filter the json on the python side, but you can easily turn off the `dynamic` mapping in elasticsearch so that it will ignore fields not defined in the mappings (1, just set `dynamic = MetaField(False)` in the `class Meta`), alternatively also add source filtering to drop unwanted fields (2).

Hope this helps!

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#index
1 - https://www.elastic.co/guide/en/elasticsearch/reference/6.2/dynamic.html
2 - https://www.elastic.co/guide/en/elasticsearch/reference/6.2/mapping-source-field.html#include-exclude

**Comment by rohansb** [comment]
Awesome! (1) & (2) Exactly i was looking for. Thanks a bunch @HonzaKral
