### ISSUE TITLE
[es6] default doc_type should be '_doc' instead of 'doc'

### ISSUE THREAD

**Issue by okke-formsma** [elastic/elasticsearch-dsl-py#877]
According to the elasticsearch 6 migration documentation [0], the new default _type will be '_doc', not 'doc' as the current elasticsearch_dsl documentation [1] suggests.

0: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
1: http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html?highlight=aliases#class-meta-options

**Comment by HonzaKral** [comment]
Thanks @okke-formsma, this was an oversight from my side. Now I am hesitant to change it though since it would be backwards incompatible change. It is also not needed because with upgrade to elasticsearch `7.x` the underlying library `elasticsearch-py` will make sure that the pats are correct regardless of the type names so we don't actually need to prepare for the type deprecation.
