### ISSUE TITLE
Set pipeline on DocTypes

### ISSUE THREAD

**Issue by OskarPersson** [elastic/elasticsearch-dsl-py#886]
I'm using `DocTypes` together with [elasticsearch-py](https://github.com/elastic/elasticsearch-py) to create [bulk requests](http://elasticsearch-py.readthedocs.io/en/master/helpers.html#bulk-helpers). Now I'm trying to set different pipelines for different DocTypes before using them in the the bulk request. How do I do that?

I've tried `MyDocType(_pipeline='my-ingest-pipeline', ...)` but that gets used as data instead of an action parameter in the bulk request.

**Comment by WisdomPill** [comment]
Hi, 
you have to add the pipeline in the kwargs of the save method as the kwargs are set to query params on the final query if they have one of the following keys ('op_type', 'parent', 'pipeline', 'refresh', 'routing', 'timeout', 'timestamp', 'ttl', 'version', 'version_type', 'wait_for_active_shards'). Otherwise you can set the Meta class of the doc of one of the latter keys to the appropriate value because jwargs and meta atributes are merged before sending the request to elasticsearch.

Hope it helps, Anas

**Comment by HonzaKral** [comment]
Thank you @WisdomPill for answering!

Currently we don't support the pipeline directly since there is little need for it when you are interfacing with `elasticsearch` from fully featured language like python. In that case I would recommend you put your logic into `save` or `clean` methods.

If you still wish to use `pipeline` with `bulk` then I would suggest you override `to_dict` or, better, wrap the call into something that would add this key if desired.

**Comment by assem-ch** [comment]
No support for this yet?
