### ISSUE TITLE
Suggestions are not working

### ISSUE THREAD

**Issue by robert197** [elastic/elasticsearch-dsl-py#903]
I tried to get term suggestions like its documented in the documentation. 
```
s = Search()
s.suggest('my_suggestion', 'edavo', term={'field': 'name'})
suggestions = s.execute_suggest()
pprint(suggestions.to_dict())
# prints {'_shards': {'failed': 0, 'skipped': 0, 'successful': 11, 'total': 11}}
```
i need the strings of term suggestions. im not able to get them. i also tried with 
```
suggestions = s.execute()
```
and suggestions.suggest is not defined... 

please help me! maybe we should update documentation or is there a bug?

**Comment by andrewwatts** [comment]
Hi @HonzaKral I can reproduce suggestions not working with the following:

```python 

client = ElasticSearch()
suggest = Search(using=client).suggest("foo", "man", completion={"field": "text_address_suggest"})

print suggest.to_dict()

# output is
# {'query': {'match_all': {}},
# 'suggest': {'foo': {'completion': {'field': 'text_address_suggest'},
#   'text': 'man'}}}

for hit in suggest.exectue():
    print hit

print suggest.to_dict()

# output is
# {'query': {'match_all': {}},
# 'suggest': {'foo': {'completion': {'field': 'text_address_suggest'},
#   'text': 'man'}}}

```

I believe the problem is that `to_dict` always includes `'query': {'match_all': {}}`: https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L614

For reference, executing the following via curl produces results i want:

```bash

curl --request POST \
  --url 'http://localhost:9200/e3-properties-2018-06-14/_search?pretty=' \
  --header 'content-type: application/json' \
  --data '{
	"suggest": {
		"foo": {
			"text": "2005 C",
			"completion": {
				"field": "text_address_suggest"
			}
		}
	}
}
'

```

However, the following curl command generates wrong results, and matches what the `to_dict` method is returning.

```bash

curl --request POST \
  --url 'http://localhost:9200/e3-properties-2018-06-14/_search?pretty=' \
  --header 'content-type: application/json' \
  --data '{
	"query": {
		"match_all": {}
	},
	"suggest": {
		"foo": {
			"text": "2005 C",
			"completion": {
				"field": "text_address_suggest"
			}
		}
	}
}
'
```

I'm not sure how to work around this yet, but it seems there is a bug by includes the "match_all" query in the suggestion search

**Comment by andrewwatts** [comment]
As I play with this some more I've realized what I'm expecting is that if I extend `DocType` to get a model-like class and call `MyDocType.search().suggest(...).execute()` I get back an iterable of `MyDocType` instances that came from `suggest` instead of `hits`.  Because, that is what the suggest `_search` via curl does.   ie: if the `_search` body only includes `suggest` and does not include `query` then elastic search returns the suggest results as `hits`.

So, maybe a `Response` should have a `suggest` property that can be iterated over, similar to `hits` and `aggs`.  But then i'm not sure what happens to `__iter__`, if anything. Alternatively, as I mentioned above `to_dict` always adds a default `match_all` query, and maybe that should change.

**Comment by HonzaKral** [comment]
The `Response` object provides access to any and all fields that have been returned by elasticsearch. For convenience there is a shortcut that allow to iterate over the `hits` as that is both most common and also easy to do. For other parts of the response, like aggregations or suggestions, you need to access them explicitly like `response.suggest.foo.options`.

Hope this helps!
