### ISSUE TITLE
[Question] `Meta.doc_type` not recommended to change?

### ISSUE THREAD

**Issue by vinayan3** [elastic/elasticsearch-dsl-py#908]
The (docs)[https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#class-meta-options] don't recommend changing the `Meta.doc_type`. Were they any reasons for this? 

I am implementing a parent and child relationship index to see how it performs on my data.

**Comment by HonzaKral** [comment]
We do not recommend changing the `doc_type` since elasticsearch doesn't support multiple doc types per index any more so it is not useful.

To implement Parent/Child relationships please see the `examples` directory on the `meta-index` branch which has an example of that with `6.x`.

Hope this helps!

**Comment by vinayan3** [comment]
Thank you. It totally does!
