### ISSUE TITLE
Documentation Questions/Suggestions

### ISSUE THREAD

**Issue by fernando-mc** [elastic/elasticsearch-dsl-py#911]
@HonzaKral Just started using using the high level client and I have a few questions/suggestions.

**Suggestions**
The use of `Q` is assumed in the documentation but at no point I could find it it imported in the examples. Eventually I found it, but within the documentation might be good to include it. Usually I expect to be able to run the documentation code from a to z with no modifications except to my specific data names and have it work.

**Questions**
I noticed in another issue that you're looking for help with documentation? I'm happy to contribute to the documentation with a few examples as I answer my own questions and use the tool for my own purposes. 

My experience is with AWS - which offers a free tier that includes using the ElasticSearch service. Would there be interest in a guide that uses that as a standard simply to get a free cluster up and running?

I have some data sets for other projects I could make available to demonstrate a few concepts with. The only limitation I have right now is that I am myself trying to learn the ins and outs of the DSL and would appreciate feedback on the examples I'm creating to make sure they're in line with the best practices and use of ElasticSearch and the Python DSL itself.

**Comment by HonzaKral** [comment]
Thanks for the suggestions, I added the imports to the docs in 13a470aa1cc788d50ccba430f63118444bf4cdd0.

> ... get a free cluster up and running?

The `AWS` service doesn't support the entire feature set of elasticsearch so I would like to avoid pointing people to it. We can, however, point to the elastic cloud (https://cloud.elastic.co/) where you can also get a free cluster up and running with a free account. We could also include an information on how to run elasticsearch easily via docker + a link to the official docs.

> I'm happy to contribute to the documentation with a few examples  ...

Any documentation fixes, or even pointers to what doesn't work well, are more than welcome. I would also be happy to help with feedback and answering questions...

There are a bunch of example coming as part of #840 that I hope will help, we also have a test dataset in the tests (documents representing early `git` history of the project), I would like to avoid dragging in another dataset so that we can keep things simple.

Thank you very much for your interest and useful suggestions, please do not hesitate and send more and/or ask any questions.

I will close this issue now as the suggestions have been implemented and we can continue the discussion either here or under individual tickets for the separate steps.

**Comment by fernando-mc** [comment]
Thanks for the quick additions! I think those will help ease some newcomers in!

As for the other things - point taken! Doesn't make sense to focus on a separate proprietary stack - I just didn't realize Elastic had a free trial 😬. 

Sounds like you have a lot of stuff coming in #840 so I'll just keep an eye on that and read stuff over after you publish the new stuff! Thanks for your work!
