### ISSUE TITLE
Pass index, doc_types, using in FacetedSearch initialization

### ISSUE THREAD

**Issue by safwanrahman** [elastic/elasticsearch-dsl-py#916]
Currently, its not possible to pass `index`, `doc_types`,  `using` paramteres while initializing the `FacetedSearch`. So this things can not modified while initializing the object.

There should be a way to customize the values while initialization. It should take parameters like [`Search`](http://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Search).

Currently, I am doing it in following way

```python
class ProjectSearch(FacetedSearch):
    fields = ['name^5', 'description']
    facets = {......}

    def __init__(self, using, index, doc_types, model, **kwargs):
        self.using = using
        self.index = index
        self.doc_types = doc_types
        super(ProjectSearch, self).__init__(**kwargs)
```
@HonzaKral If you agree on the implementation, I would be happy to send a patch.

**Comment by HonzaKral** [comment]
I am not sure that this is needed since there is another solution that you just posted here. I am perfectly ok with non-standard use cases (like having dynamic index name) requiring overriding of some methods as long as those methods are explicitly documented - which is the case here.

I will close the issue now, if there are some other reasons why you'd like to see this in the library itself, or if there are other users who would find this useful, please feel free to reopen.

Thank you!
