### ISSUE TITLE
Consider release multiple packages for different major versions?

### ISSUE THREAD

**Issue by shuoli84** [elastic/elasticsearch-dsl-py#919]
Underlying elasticsearch-py is doing this, there are elasticsearch2 elasticsearch5 packages on pypi. Should elasticsearch-dsl do the samething? We have a relative large code base and multiple versions of elasticsearch clusters, this will make our lives much easier.

**Comment by HonzaKral** [comment]
Thanks for raising the issue! 
I understand the reasoning behind this but I don't think it is required at this point. With the functionality of `elasticsearch-dsl` the incompatibilities tend to be more in what the users decide to do with it rather than the code itself. It should always be possible, with some care, to use a newer version of the library with older elasticsearch releases. I would be completely open to expanding some of the API if it would make that task easier. I am afraid, however, that we currently don't have the bandwidth to support multiple releases.

**Comment by priyadarshiniravi** [comment]
Need the same thing too.

**Comment by potasiak** [comment]
My team needs it too.

We have created a fork of the repository and prepared a branch where we have replaced usage of the `elasticsearch` package with the `elasticsearch2`, as we have lots of legacy code running on that specific version. The tests are passing, and we have managed to successfully run our (quite big, developed for 7+ years now) application with it.

In my opinion release of the `elasticsearchX-dsl` packages is necessary, as otherwise there's no consistency with the `elasticsearchX` packages. I would be happy to create pull requests for all available versions and help maintain it. The maintenance itself would be exactly the same as in the [elasticsearch-py](https://github.com/elastic/elasticsearch-py) repo.

I have also noticed that @HonzaKral and @sethmlarson have [already reserved names for some of these packages in PyPI](https://pypi.org/search/?q=elasticsearch-dsl), so I'm not sure if there's anyone else currently working on that issue.

Please let me know what you think about it. It would be great if we could do that officially at least for the versions that are not actively developed anymore (e.g. elasticsearch-dsl 2.x [has not changed in over 3 years](https://github.com/elastic/elasticsearch-dsl-py/commits/2.x)).

Also, it's worth to mention it's a duplicate of this issue: #412
