### ISSUE TITLE
Deprecation of mapping types  doc vs _doc

### ISSUE THREAD

**Issue by Benoss** [elastic/elasticsearch-dsl-py#926]
In the last merge the mapping types were deprecated in order to comply with ES 7.0

I am a bit confused between "doc" and "_doc", I think ES-dsl-py is using "doc" as the default index type (and you cannot change it anymore)

https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types

`Indices created in 6.x only allow a single-type per index. Any name can be used for the type, but there can be only one. The preferred type name is _doc, so that index APIs have the same path as they will have in 7.0: PUT {index}/_doc/{id} and POST {index}/_doc`

Does this mean that the documents created with ES dsl py will have not work with the ES7  POST {index}/_doc ?

**Comment by HonzaKral** [comment]
The API paths will indeed change for ES7, which is my oversight, but it shouldn't really be an issue since we have the option of shielding the user from that by going through the python API which is responsible for constructing the path. Overall the user should not be impacted by elasticsearch 7. We will of course publish a new version of es-dsl for elasticsearch 7 which will hide any potential incompatibilities if possible.

Does this answer your question? Please feel free to reopen with further details

You can also see https://github.com/elastic/elasticsearch-dsl-py/issues/877 for another instance of this.

**Comment by rnapier** [comment]
Does this mean that in order to the use `.get` interface, the following needs to be included in each document class:

```
class Model(Document):
    class Meta:
        doc_type = "_doc"

    class Index:
        name = "model"
        doc_type = "_doc"
```

Without this, `Model.get(id=id)` won't find anything (since it'll look for "doc" rather than "_doc"). Is there a simpler approach?

**Comment by Mekk** [comment]
I tried using elasticseach-dsl for the first time and got errors caused by ES 7.0 incompatibility (my server is 7.0 already). Both attempt to create mapping, and attempt to search fail.
Are fixes made here released?

**Comment by HonzaKral** [comment]
@Mekk sorry for the delays, there is a `7.0` branch that supports these operations but it is still missing some functionality (`_version`/`_seq_no` handling in `Document.save`).

**Comment by littlehome-eugene** [comment]
I need a way to change 'doc' to '_doc' .. 
it seems to be static 

` body['doc'] = {`

**Comment by AirrBear** [comment]
> I need a way to change 'doc' to '_doc' ..
> it seems to be static
> 
> ` body['doc'] = {`

@littlehome-eugene  Have you figured out a way to do so? I have the same problem
