### ISSUE TITLE
Filtering by date using dsl-py

### ISSUE THREAD

**Issue by admitstack** [elastic/elasticsearch-dsl-py#928]
`count = 0
	client = Elasticsearch(url, http_auth = (username, password), verify_certs = False)
	s = Search(using=client, index = set_index).source(['metadata.Year'])`

As seen in the code above, my dates are listed in the metadata.Year. I would like to be able to return the number of results in a specific year. I am thinking of using .filter but not sure what the best option is. Also, I don't know if the values in the column are in datetime format, or if they are just strings.

**Comment by HonzaKral** [comment]
Unfortunately in order to do that you need to know what your field is mapped at. You can always find out by trying `client.indices.get_mapping(index=set_index)` and looking for the results. If it is properly mapped as `date` you can do:

`s = s.filter('range', metadata__Year={'gte': date(2018, 1, 1), 'lt': date(2019, 1, 1)})`

hope this helps!

**Comment by admitstack** [comment]
Thanks, the I was able to check the type, it is mapped as long. When I
switched 'date' to 'long' in my code, I got the error message 'SyntaxError:
keyword can't be an expression'.

**Comment by HonzaKral** [comment]
If it is mapped as `long` then it is just the year so you can query it like: `s = s.filter('term', metadata__Year=2018)`
