### ISSUE TITLE
Don't use Q shortcut in FacetedSearch to allow for fields with __

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch-dsl-py#954]
see https://github.com/elastic/elasticsearch-dsl-py/issues/28#issuecomment-405728255 for details

**Comment by mihalikv** [comment]
@HonzaKral  You changed it to classes that extends from Query and Query extends from DslBase where expand_to_dot is applied. So it is still not possible to use double underscore in FacetSearch am I right ?

**Comment by HonzaKral** [comment]
That is correct, you need to specify the proper field name with `.`, since it is passed around as a string and not a python identifier there is no need for the `__`.

**Comment by mihalikv** [comment]
I already override TermsFacet because I have field "category__id" and I am not able to add facet filter.

**Comment by HonzaKral** [comment]
wait, you have a field like that in your document? Then that should work just fine, this change was exactly to allow for that to work, there should be no need for any forking. Prior to this change `__` would get translated to `.` but now it should just be passed through correctly.

Sorry for misunderstanding earlier..

**Comment by mihalikv** [comment]
Yes, a problem is with field with double underscore in it. I am not sure if it is my fault but from reading a code it's right behavior. Because it is extended from DslBase and expand to dot is applied and double underscore is replaced by dot.

https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/query.py#L36 Here is base query extending from DslBase and here 
https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/utils.py#L199 
we have DslBase with constructor where replacement is used.

**Comment by HonzaKral** [comment]
You are indeed correct, we should be passing `_expand__to_dot=False`. I implemented it in e74ab2c42d3255a0443a009e1cb55ddea559afec, could you please verify that it fixes your issue?

Thank you!

**Comment by mihalikv** [comment]
This is exactly same code that I am currently using in custom overridden TermsFacet so it should work. Thank you for your help :)

**Comment by HonzaKral** [comment]
Thank you for raising the issue, @mihalikv !
