### ISSUE TITLE
index not mapped again after field change

### ISSUE THREAD

**Issue by Bjorninn1** [elastic/elasticsearch-dsl-py#968]
Let´s say I have

```
class SomeIndexing(DocType):
    main_text = Text(fielddata=True)
    time_written = Text(fielddata=True)
 ```

```
def bulk_indexing():
    SomeIndexing.init(index='my-index')
    es = Elasticsearch()
    bulk(client=es, actions=(b.indexing()
    for b in models.MyObject.objects.all().iterator()))
```

```
class MyObject(models.Model):

     main_text = models.CharField(max_length=1000000, null=True, blank=True)
     time_written = models.DateField(null=True, blank=True)

    def indexing(self):
        obj = TextObjectIndexing01(
            meta={'id': self.id},
            main_text=self.main_text,
        )
        obj.save(index='textobject2-index')
        return obj.to_dict(include_meta=True)
```

Then I call bulk_indexing() to have data registered. 

Now if I change the time_written in SomeIndexing to `time_written = Date()` , and then delete my-index and call bulk_indexing() again, the field type will not be changed to Date when I map the index. Instead it is mapped as Text (the same as before making the change). 

But if I change my-index to my-index2 before bulk_indexing, the field will be mapped correctly. 

I just wanted to point this out since it was not obvious for me to change the index name after making a field change and thought it might possibly be of use for others knowing about it. The issue may be closed.

**Comment by HonzaKral** [comment]
If you want to affect any mapping changes then you need to call `SomeIndexing.init()`, otherwise the index is not created in elasticsearch. Just indexing the data won't carry any information about the mappings.

Also in your code you seem to be saving each document twice - once by calling `obj.save()` you are saving each document individually and the second time by passing it to `bulk` helper, this is most inefficient.

Hope this helps!

**Comment by Bjorninn1** [comment]
Thank you very much.
