### ISSUE TITLE
Cannot create an empty nested type

### ISSUE THREAD

**Issue by ChaosCA** [elastic/elasticsearch-dsl-py#970]
Hey, I'm trying to initialize a ES Index. This is my model for example:

```python
class Sensor(InnerObjectWrapper):
    name = Keyword()

class MIssion(DocType):
    name = Keyword()
    sensor = Object(Sensor)

    class Meta:
        index = 'my_index'
```

Note this is for ES5 which is why I am using InnerObject not InnerDoc.

I can see in the debug the following is being sent:
```
DEBUG - > {"properties": "sensor": {"type": "object"}, "name": {"type": "keyword"}}}
DEBUG - < {"error":{"root_cause":[{"type":"i_o_exception","reason":"Cannot create an empty nested type (not supported)"}],"type":"i_o_exception","reason":"Cannot create an empty nested type (not supported)","caused_by":{"type":"invalid_request_exception","reason":"Cannot create an empty nested type (not supported)"}},"status":500}
```

Which is weird because it's not posting any of the other properties for sensor along with it.

One additional question, in order to search for a sensor name, I tried the following syntax:
```python
s = Mission.sensor.search().query('term', name='something')
s.execute()
```

But I get an error that the sensor attribute doesn't exist. Is there another syntax that this library expects?

Thank you

**Comment by HonzaKral** [comment]
If you want to query inner objects (`Nested` is different) you just need to refer to the fields using the `.` notation so `sensor.name` instead of just `name`. To make it simpler the `query` method allows you to use `__` instead of `.`. Your query will then look like:

`Mission.search().query('term', sensor__name='something')`

Hope this helps!
