### ISSUE TITLE
When adding an analyzer to a field, boosting fields in queries no longer works.

### ISSUE THREAD

**Issue by adela-neacsu** [elastic/elasticsearch-dsl-py#973]
Hello,

As I was trying to add a `snowball` analyzer to some of my fields, I noticed that adding the analyzer parameter makes boosting in queries to no longer work. Here is an example :

```python

class Person(BaseIndex):
    name = dsl.Text()
    biography = dsl.Text(analyzer='snowball')
    age = dsl.Short()
________

search_fields = [
    'name^3',
    'biography^2',
    'age',
]
```

In the case above, the boosting on `biography` (x2) no longer works. I can solve this by adding the boost directly onto the field, like `biography = dsl.Text(analyzer='snowball', boost=2)`, but this behavior has been deprecated and is no longer recommended by Elasticsearch (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-boost.html) why).

Any solutions?

Thanks,
Adela.

**Comment by HonzaKral** [comment]
Hello Adela,

Can you please clarify what you mean by "no longer works"? Are the scores the same with and without the boost? Is the result set different?

Thanks!

**Comment by adela-neacsu** [comment]
Hi HonzaKral,

Yes, that is what I mean. No matter the boost, the scores remain exactly the same when adding the analyzer. I even tried with very high numbers, like 1000, and there are absolutely no differences.

Without the analyzer, however, I get different scores when boosting. I can post an example if you need me to.

Thanks.

**Comment by HonzaKral** [comment]
And is there actual match on that field? Could it be that with the analyzer only `name` or `age` match so that any boost on `biagraphy` is ignored?

Analyzer is always applied to `Text` field. Specifying different analyzer just changes the type of analysis being applied and should never influence the boosting capabilities.

An example would be great!

**Comment by adela-neacsu** [comment]
@HonzaKral , I created a short gist here with an example : [ES example](https://gist.github.com/nqryn/a1366c3b74e7327eb9b75788ae26ee46)

I actually discovered that the issue is not when adding an analyzer to a certain field, but having different analyzers for the fields that are used in a query.

For example, I ran that code having either no analyzer for title and body (which meant it was default), having the same analyzer, or having different ones. The results were always the same when having the same vs different analyzers, with regards to boosting. You can check out my attached print screen.

![screen shot 2018-08-06 at 15 23 49](https://user-images.githubusercontent.com/40423932/43716572-4305c3ec-998d-11e8-83da-cbb84bb543b0.png)

**Comment by HonzaKral** [comment]
Thank you for the code!

The problem is that you are using `cross_fields` which has different approach to analysis so that two fields with different analyzers affect it differently. See (0) for detail on `cross_field` behavior.

If you remove the `type=cross_field` from your multi match, it works as expected.

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#_literal_cross_field_literal_and_analysis

**Comment by adela-neacsu** [comment]
@HonzaKral, indeed, I was not aware of this. Thank you for your help!
